In [1]:
import numpy as np

In [2]:
a = np.array([1., 2., 3.])
b = np.array([2., 2., 2.])
a * b

array([2., 4., 6.])

In [3]:
a = np.array([1., 2., 3.])
b = 2.0  # more efficient (with stretching)
a * b

array([2., 4., 6.])

In [6]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

b = np.array([1.0, 2.0, 3.0])  # more efficient (with stretching) then:

c = np.array([[1.0, 2.0, 3.0],
             [1.0, 2.0, 3.0],
             [1.0, 2.0, 3.0],
             [1.0, 2.0, 3.0]])

(a + b) == (a + c)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

# a + b mismash
c = a[:, np.newaxis] + b  # (4, 1) + (3)
c, c.shape

(array([[ 1.,  2.,  3.],
        [11., 12., 13.],
        [21., 22., 23.],
        [31., 32., 33.]]),
 (4, 3))

In [13]:
from numpy import array, argmin, sqrt, sum

observation = array([111.0, 188.0])
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation  # the broadcast happens here
dist = sqrt(sum(diff**2, axis=-1))
argmin(dist), codes.shape, observation.shape, diff.shape

(0, (4, 2), (2,), (4, 2))