In [1]:
import numpy as np

In [2]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [3]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

In [6]:
z = np.array([1, 2, 3], dtype='d')
z, type(z), type(z[0])

(array([1., 2., 3.]), numpy.ndarray, numpy.float64)

In [16]:
z = z.astype(np.bool_)

In [17]:
z.dtype

dtype('bool')

In [22]:
np.issubdtype(z[0], np.bool_), np.issubdtype(z[0], np.integer)

(True, False)

In [27]:
z = np.array(["hello", "world!"])
z

array(['hello', 'world!'], dtype='<U6')

In [29]:
z = np.array([b'some'])
z

array([b'some'], dtype='|S4')

In [36]:
z = np.array(["hello", "world"], dtype="S7").tobytes()
z, len(z)

(b'hello\x00\x00world\x00\x00', 14)

In [41]:
x = [b"hello\0\0", b"world\x00"]
a = np.array(x, dtype='S7')
x, a

([b'hello\x00\x00', b'world\x00'], array([b'hello', b'world'], dtype='|S7'))

In [42]:
x[0] == a[0]

False

In [43]:
a = np.array(x, dtype="V7")
a

array([b'\x68\x65\x6C\x6C\x6F\x00\x00', b'\x77\x6F\x72\x6C\x64\x00\x00'],
      dtype='|V7')

In [44]:
a[0] == np.void(x[0])

array(True)

In [45]:
a[0]

void(b'\x68\x65\x6C\x6C\x6F\x00\x00')

In [47]:
np.power(100, 9, dtype=np.int64)

1000000000000000000

In [48]:
np.power(100, 9, dtype=np.int32)

-1486618624

In [49]:
np.iinfo(int)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [50]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [51]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [52]:
np.power(100, 100, dtype=np.float64)

1e+200

In [55]:
np.finfo(np.longdouble)

finfo(resolution=1e-18, min=-1.189731495357231765e+4932, max=1.189731495357231765e+4932, dtype=float128)

In [57]:
1 + np.finfo(np.longdouble).eps

1.0000000000000000001