In [1]:
import pandas as pd
import numpy as np

/home/kajetan/anaconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
index = pd.date_range("1/1/2000", periods=8)
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])
df

A         B         C
2000-01-01  0.271689  1.102246  0.697307
2000-01-02 -0.256953 -1.181383  1.515807
2000-01-03  0.878240  1.066269 -0.211037
2000-01-04  0.877827 -1.612715 -0.248709
2000-01-05 -0.491206  0.139513  1.079171
2000-01-06 -0.377065  0.612793 -0.002603
2000-01-07  0.330015  1.090078  1.502033
2000-01-08 -1.196474  0.175123  2.109614

In [3]:
s

a   -0.812946
b    0.750094
c    0.631343
d    1.168199
e   -0.066984
dtype: float64

In [4]:
index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [5]:
s.head(2), s.tail(3)

(a   -0.812946
 b    0.750094
 dtype: float64,
 c    0.631343
 d    1.168199
 e   -0.066984
 dtype: float64)

In [6]:
df[:2]

A         B         C
2000-01-01  0.271689  1.102246  0.697307
2000-01-02 -0.256953 -1.181383  1.515807

In [7]:
df.columns = [x.lower() for x in df.columns]
df

a         b         c
2000-01-01  0.271689  1.102246  0.697307
2000-01-02 -0.256953 -1.181383  1.515807
2000-01-03  0.878240  1.066269 -0.211037
2000-01-04  0.877827 -1.612715 -0.248709
2000-01-05 -0.491206  0.139513  1.079171
2000-01-06 -0.377065  0.612793 -0.002603
2000-01-07  0.330015  1.090078  1.502033
2000-01-08 -1.196474  0.175123  2.109614

In [8]:
df.a

2000-01-01    0.271689
2000-01-02   -0.256953
2000-01-03    0.878240
2000-01-04    0.877827
2000-01-05   -0.491206
2000-01-06   -0.377065
2000-01-07    0.330015
2000-01-08   -1.196474
Freq: D, Name: a, dtype: float64

In [9]:
df

a         b         c
2000-01-01  0.271689  1.102246  0.697307
2000-01-02 -0.256953 -1.181383  1.515807
2000-01-03  0.878240  1.066269 -0.211037
2000-01-04  0.877827 -1.612715 -0.248709
2000-01-05 -0.491206  0.139513  1.079171
2000-01-06 -0.377065  0.612793 -0.002603
2000-01-07  0.330015  1.090078  1.502033
2000-01-08 -1.196474  0.175123  2.109614

In [12]:
s.array

<NumpyExtensionArray>
[  -0.812946419165515,   0.7500939782966553,   0.6313432743040721,
   1.1681992199938875, -0.06698355833191269]
Length: 5, dtype: float64

In [16]:
s.array

<NumpyExtensionArray>
[  -0.812946419165515,   0.7500939782966553,   0.6313432743040721,
   1.1681992199938875, -0.06698355833191269]
Length: 5, dtype: float64

In [14]:
s.index.array

<NumpyExtensionArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

In [17]:
np.asarray(s) == s.to_numpy()

array([ True,  True,  True,  True,  True])

In [19]:
ser = pd.Series(pd.date_range("2000", periods=2, tz="CET"))
ser

0   2000-01-01 00:00:00+01:00
1   2000-01-02 00:00:00+01:00
dtype: datetime64[ns, CET]

In [21]:
ser.to_numpy(dtype=object)

array([Timestamp('2000-01-01 00:00:00+0100', tz='CET'),
       Timestamp('2000-01-02 00:00:00+0100', tz='CET')], dtype=object)

In [22]:
ser.to_numpy(dtype="datetime64[ns]")

array(['1999-12-31T23:00:00.000000000', '2000-01-01T23:00:00.000000000'],
      dtype='datetime64[ns]')

In [25]:
pd.set_option("compute.use_numexpr", False)

In [26]:
df = pd.DataFrame(
    {
        "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
        "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
    }
)

df

one       two     three
a  1.174030  0.678128       NaN
b -0.563444  0.571915 -0.533035
c -1.396908  0.687476  0.924228
d       NaN  0.580159  1.171627

In [27]:
row = df.iloc[1]
column = df["two"]
row, column

(one     -0.563444
 two      0.571915
 three   -0.533035
 Name: b, dtype: float64,
 a    0.678128
 b    0.571915
 c    0.687476
 d    0.580159
 Name: two, dtype: float64)

In [31]:
df.sub(row, axis="columns") == df.sub(row, axis=1)

one   two  three
a   True  True  False
b   True  True   True
c   True  True   True
d  False  True   True

In [32]:
df.sub(column, axis="index") == df.sub(column, axis=0)

one   two  three
a   True  True  False
b   True  True   True
c   True  True   True
d  False  True   True

In [33]:
dfmi = df.copy()
dfmi.index = pd.MultiIndex.from_tuples(
    [(1, "a"), (1, "b"), (1, "c"), (2, "a")], names=["first", "second"]
)

dfmi

one       two     three
first second                              
1     a       1.174030  0.678128       NaN
      b      -0.563444  0.571915 -0.533035
      c      -1.396908  0.687476  0.924228
2     a            NaN  0.580159  1.171627

In [37]:
dfmi.sub(column, axis=0, level="second")

one      two     three
first second                             
1     a       0.495901  0.00000       NaN
      b      -1.135360  0.00000 -1.104950
      c      -2.084384  0.00000  0.236752
2     a            NaN -0.09797  0.493498

In [38]:
s = pd.Series(np.arange(10))
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [40]:
div, rem = divmod(s, 3)
div, rem

(0    0
 1    0
 2    0
 3    1
 4    1
 5    1
 6    2
 7    2
 8    2
 9    3
 dtype: int64,
 0    0
 1    1
 2    2
 3    0
 4    1
 5    2
 6    0
 7    1
 8    2
 9    0
 dtype: int64)

In [41]:
idx = pd.Index(np.arange(10))
idx

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [42]:
div, rem = divmod(idx, 3)
div, rem

(Index([0, 0, 0, 1, 1, 1, 2, 2, 2, 3], dtype='int64'),
 Index([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype='int64'))

In [43]:
np.nan == np.nan

False

In [46]:
(df + df).equals(df * 2)

True

In [48]:
df1 = pd.DataFrame({"col": ["foo", 0, np.nan]})
df2 = pd.DataFrame({"col": [np.nan, 0, "foo"]}, index=[2, 1, 0])
df1

col
0  foo
1    0
2  NaN

In [49]:
df2

col
2  NaN
1    0
0  foo

In [51]:
df1.equals(df2.sort_index())

True

In [52]:
df

one       two     three
a  1.174030  0.678128       NaN
b -0.563444  0.571915 -0.533035
c -1.396908  0.687476  0.924228
d       NaN  0.580159  1.171627

In [58]:
df.sum(axis=0, skipna=False)

one           NaN
two      2.517679
three         NaN
dtype: float64

In [59]:
df.sum(axis=1, skipna=True)

a    1.852158
b   -0.524564
c    0.214796
d    1.751786
dtype: float64

In [62]:
data = np.arange(10)
data.cumsum(), data.cumprod()

(array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [63]:
df

one       two     three
a  1.174030  0.678128       NaN
b -0.563444  0.571915 -0.533035
c -1.396908  0.687476  0.924228
d       NaN  0.580159  1.171627

In [67]:
np.mean(df["one"].to_numpy()), np.mean(df["two"].to_numpy())

(nan, 0.6294196822138629)

In [68]:
np.mean(df["one"].nunique())

3.0

In [69]:
series = pd.Series(np.random.randn(1000))
series[::2] = np.nan
series.describe()

count    500.000000
mean      -0.025446
std        0.973699
min       -2.451071
25%       -0.721998
50%       -0.053101
75%        0.675731
max        2.683392
dtype: float64

In [70]:
series.describe(percentiles=[0.05, 0.25, 0.85, 0.90, 0.95])

count    500.000000
mean      -0.025446
std        0.973699
min       -2.451071
5%        -1.599305
25%       -0.721998
50%       -0.053101
85%        1.059735
90%        1.222471
95%        1.531513
max        2.683392
dtype: float64

In [71]:
s = pd.Series(["a", "a", "b", "b", "a", "a", np.nan, "c", "d", "a"])
s.describe()

count     9
unique    4
top       a
freq      5
dtype: object

In [72]:
frame = pd.DataFrame({"a": ["Yes", "Yes", "No", "No"], "b": range(4)})
frame.describe(include=["object"])

a
count     4
unique    2
top     Yes
freq      2

In [73]:
frame.describe(include=["number"])

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [75]:
frame.describe(include="all")

a         b
count     4  4.000000
unique    2       NaN
top     Yes       NaN
freq      2       NaN
mean    NaN  1.500000
std     NaN  1.290994
min     NaN  0.000000
25%     NaN  0.750000
50%     NaN  1.500000
75%     NaN  2.250000
max     NaN  3.000000

In [78]:
s1 = pd.Series(np.random.randn(5))
s1

0    0.077338
1    0.783076
2    1.426412
3   -1.483359
4    0.384448
dtype: float64

In [79]:
s1.idxmin(), s1.idxmax()

(3, 2)

In [83]:
df1 = pd.DataFrame(np.random.randn(5, 3), columns=list("ABC"))
df1

A         B         C
0  0.076005  0.603352 -0.856868
1 -0.508189  1.199725  0.180339
2  0.337323 -2.526947 -0.054166
3 -1.136100  0.904992  0.418666
4 -0.563723 -0.379387  1.121832

In [87]:
data = np.random.randint(0, 7, size=50)
data

array([2, 3, 4, 3, 3, 6, 3, 0, 2, 6, 5, 3, 3, 6, 2, 5, 3, 1, 0, 1, 4, 5,
       5, 0, 0, 5, 1, 1, 6, 1, 2, 6, 1, 1, 4, 3, 4, 1, 4, 4, 4, 0, 2, 2,
       2, 6, 1, 3, 4, 2])

In [90]:
s = pd.Series(data)
s.value_counts(), s.value_counts().idxmax(), s.value_counts().idxmin()

(3    9
 1    9
 2    8
 4    8
 6    6
 0    5
 5    5
 Name: count, dtype: int64,
 3,
 0)

In [91]:
s.mode()

0    1
1    3
dtype: int64

In [92]:
arr = np.random.randn(20)
arr

array([-0.97336209, -0.56924011,  0.43809642,  0.34013435,  1.01741892,
       -0.07916706,  1.97832814,  0.29287554, -0.88720838,  0.1118557 ,
        0.26381609, -1.07095227,  0.7546941 , -0.60929543,  0.52455767,
       -1.27176461,  0.4034245 ,  1.51251366, -1.33714629,  0.13884692])

In [93]:
pd.cut(arr, 4)

[(-1.34, -0.508], (-1.34, -0.508], (0.321, 1.149], (0.321, 1.149], (0.321, 1.149], ..., (-1.34, -0.508], (0.321, 1.149], (1.149, 1.978], (-1.34, -0.508], (-0.508, 0.321]]
Length: 20
Categories (4, interval[float64, right]): [(-1.34, -0.508] < (-0.508, 0.321] < (0.321, 1.149] < (1.149, 1.978]]

In [98]:
len(arr), len(pd.cut(arr, 4)), 

(20, 20)

In [100]:
factor = pd.cut(arr, [-5, -1, 0, 1, 5])
factor

[(-1, 0], (-1, 0], (0, 1], (0, 1], (1, 5], ..., (-5, -1], (0, 1], (1, 5], (-5, -1], (0, 1]]
Length: 20
Categories (4, interval[int64, right]): [(-5, -1] < (-1, 0] < (0, 1] < (1, 5]]

In [102]:
arr = np.random.randn(30)
factor = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])
factor

[(-2.44, -0.824], (-0.824, 0.259], (0.259, 0.767], (-2.44, -0.824], (-0.824, 0.259], ..., (-2.44, -0.824], (-0.824, 0.259], (-0.824, 0.259], (-2.44, -0.824], (0.767, 1.949]]
Length: 30
Categories (4, interval[float64, right]): [(-2.44, -0.824] < (-0.824, 0.259] < (0.259, 0.767] < (0.767, 1.949]]

In [118]:
import statsmodels.formula.api as sm

bb = pd.read_csv("data/baseball.csv")
bb

id     player  year  stint team  lg    g   ab   r    h  ...   rbi   sb  \
0   88641  womacto01  2006      2  CHN  NL   19   50   6   14  ...   2.0  1.0   
1   88643  schilcu01  2006      1  BOS  AL   31    2   0    1  ...   0.0  0.0   
2   88645  myersmi01  2006      1  NYA  AL   62    0   0    0  ...   0.0  0.0   
3   88649  helliri01  2006      1  MIL  NL   20    3   0    0  ...   0.0  0.0   
4   88650  johnsra05  2006      1  NYA  AL   33    6   0    1  ...   0.0  0.0   
..    ...        ...   ...    ...  ...  ..  ...  ...  ..  ...  ...   ...  ...   
95  89525  benitar01  2007      2  FLO  NL   34    0   0    0  ...   0.0  0.0   
96  89526  benitar01  2007      1  SFN  NL   19    0   0    0  ...   0.0  0.0   
97  89530  ausmubr01  2007      1  HOU  NL  117  349  38   82  ...  25.0  6.0   
98  89533   aloumo01  2007      1  NYN  NL   87  328  51  112  ...  49.0  3.0   
99  89534  alomasa02  2007      1  NYN  NL    8   22   1    3  ...   0.0  0.0   

     cs  bb    so  ibb  hbp   sh   sf  gidp  
0   1.0   4   4.0  0.0  0.0  3.0  0.0   0.0  
1   0.0   0   1.0  0.0  0.0  0.0  0.0   0.0  
2   0.0   0   0.0  0.0  0.0  0.0  0.0   0.0  
3   0.0   0   2.0  0.0  0.0  0.0  0.0   0.0  
4   0.0   0   4.0  0.0  0.0  0.0  0.0   0.0  
..  ...  ..   ...  ...  ...  ...  ...   ...  
95  0.0   0   0.0  0.0  0.0  0.0  0.0   0.0  
96  0.0   0   0.0  0.0  0.0  0.0  0.0   0.0  
97  1.0  37  74.0  3.0  6.0  4.0  1.0  11.0  
98  0.0  27  30.0  5.0  2.0  0.0  3.0  13.0  
99  0.0   0   3.0  0.0  0.0  0.0  0.0   0.0  

[100 rows x 23 columns]

In [119]:
(
    bb.query("h > 0")
    .assign(ln_h= lambda df: np.log(df.h))
    .pipe((sm.ols, "data"), "hr ~ ln_h + year + g + C(lg)")
    .fit()
    .summary()
)

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     hr   R-squared:                       0.685
Model:                            OLS   Adj. R-squared:                  0.665
Method:                 Least Squares   F-statistic:                     34.28
Date:                Tue, 18 Jun 2024   Prob (F-statistic):           3.48e-15
Time:                        12:07:12   Log-Likelihood:                -205.92
No. Observations:                  68   AIC:                             421.8
Df Residuals:                      63   BIC:                             432.9
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept   -8484.7720   4664.146     -1.819      0.074   -1.78e+04     835.780
C(lg)[T.NL]    -2.2736      1.325     -1.716      0.091      -4.922       0.375
ln_h           -1.3542      0.875     -1.547      0.127      -3.103       0.395
year            4.2277      2.324      1.819      0.074      -0.417       8.872
g               0.1841      0.029      6.258      0.000       0.125       0.243
==============================================================================
Omnibus:                       10.875   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.004   Jarque-Bera (JB):               17.298
Skew:                           0.537   Prob(JB):                     0.000175
Kurtosis:                       5.225   Cond. No.                     1.49e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.49e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [120]:
df

one       two     three
a  1.174030  0.678128       NaN
b -0.563444  0.571915 -0.533035
c -1.396908  0.687476  0.924228
d       NaN  0.580159  1.171627

In [121]:
df.apply("mean", axis=1)

a    0.926079
b   -0.174855
c    0.071599
d    0.875893
dtype: float64

In [123]:
tsdf = pd.DataFrame(
    np.random.randn(1000, 3),
    columns=["A", "B", "C"] ,
    index=pd.date_range("1/1/2000", periods=1000)
)

tsdf

A         B         C
2000-01-01  0.343987 -1.633159  0.745923
2000-01-02  1.773208 -0.038124 -0.618611
2000-01-03  0.610069 -1.007778 -0.390451
2000-01-04 -0.803657 -0.520082  1.173778
2000-01-05 -0.829760 -0.444385  4.141053
...              ...       ...       ...
2002-09-22  0.602486  0.746116 -0.232446
2002-09-23 -0.631412  0.292087 -0.644771
2002-09-24 -1.042090  0.673102  0.718829
2002-09-25  0.115841  1.172464 -1.243635
2002-09-26  0.859466  0.272111 -1.951656

[1000 rows x 3 columns]

In [124]:
tsdf.apply(lambda x: x.idxmax())

A   2002-07-06
B   2000-01-11
C   2000-01-05
dtype: datetime64[ns]

In [126]:
def substract_and_divide(x, sub, divide=1):
    return (x - sub) / divide

df_udf = pd.DataFrame(np.ones((2, 2)))
df_udf.apply(substract_and_divide, args=(5,), divide=5)

0    1
0 -0.8 -0.8
1 -0.8 -0.8

In [128]:
tsdf

A         B         C
2000-01-01  0.343987 -1.633159  0.745923
2000-01-02  1.773208 -0.038124 -0.618611
2000-01-03  0.610069 -1.007778 -0.390451
2000-01-04 -0.803657 -0.520082  1.173778
2000-01-05 -0.829760 -0.444385  4.141053
...              ...       ...       ...
2002-09-22  0.602486  0.746116 -0.232446
2002-09-23 -0.631412  0.292087 -0.644771
2002-09-24 -1.042090  0.673102  0.718829
2002-09-25  0.115841  1.172464 -1.243635
2002-09-26  0.859466  0.272111 -1.951656

[1000 rows x 3 columns]

In [129]:
tsdf = tsdf[:10]
tsdf.iloc[3:7] = np.nan
tsdf

/tmp/ipykernel_1334/976029126.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tsdf.iloc[3:7] = np.nan


A         B         C
2000-01-01  0.343987 -1.633159  0.745923
2000-01-02  1.773208 -0.038124 -0.618611
2000-01-03  0.610069 -1.007778 -0.390451
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.514834 -0.092539  0.686401
2000-01-09 -0.751232 -0.097016 -0.400273
2000-01-10  1.022939  0.389140  1.690067

In [130]:
tsdf.apply(pd.Series.interpolate)

A         B         C
2000-01-01  0.343987 -1.633159  0.745923
2000-01-02  1.773208 -0.038124 -0.618611
2000-01-03  0.610069 -1.007778 -0.390451
2000-01-04  0.591022 -0.824730 -0.175081
2000-01-05  0.571975 -0.641682  0.040290
2000-01-06  0.552928 -0.458635  0.255660
2000-01-07  0.533881 -0.275587  0.471031
2000-01-08  0.514834 -0.092539  0.686401
2000-01-09 -0.751232 -0.097016 -0.400273
2000-01-10  1.022939  0.389140  1.690067

In [131]:
tsdf.agg("sum")

A    3.513806
B   -2.479476
C    1.713057
dtype: float64

In [137]:
np.sum(tsdf, axis=0) == tsdf.agg(lambda x: np.sum(x))

A    True
B    True
C    True
dtype: bool

In [138]:
tsdf["A"].agg(["sum", "mean"])

sum     3.513806
mean    0.585634
Name: A, dtype: float64

In [139]:
tsdf["A"].agg(["sum", lambda x: x.mean()])

sum         3.513806
<lambda>    0.585634
Name: A, dtype: float64

In [140]:
tsdf.agg({"A": "mean", "B": "sum"})

A    0.585634
B   -2.479476
dtype: float64

In [141]:
tsdf.agg({"A": ["mean", "min"], "B": "sum"})

A         B
mean  0.585634       NaN
min  -0.751232       NaN
sum        NaN -2.479476

In [148]:
tsdf.transform({"A": np.abs, "B": [lambda x: x + 1, "sqrt"]})

/home/kajetan/anaconda3/lib/python3.10/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)


A         B          
            absolute  <lambda>      sqrt
2000-01-01  0.343987 -0.633159       NaN
2000-01-02  1.773208  0.961876       NaN
2000-01-03  0.610069 -0.007778       NaN
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.514834  0.907461       NaN
2000-01-09  0.751232  0.902984       NaN
2000-01-10  1.022939  1.389140  0.623811

In [149]:
df4 = df.copy()

def f(x):
    return len(str(x))

    
df4["one"].map(f)

a    18
b    19
c    19
d     3
Name: one, dtype: int64

In [150]:
df4.map(f)

one  two  three
a   18   18      3
b   19   18     19
c   19   18     18
d    3   18     17

In [153]:
s = pd.Series(
    ["six", "seven", "six", "seven", "six"], index=["a", "b", "c", "d", "e"]
)

t = pd.Series({"six": 6.0, "seven": 7.0})
s

a      six
b    seven
c      six
d    seven
e      six
dtype: object

In [157]:
s = s.map(t)

In [158]:
s.reindex(["e", "b", "f", "d"])

e    6.0
b    7.0
f    NaN
d    7.0
dtype: float64

In [161]:
rs = s.reindex(df.index)
rs

a    6.0
b    7.0
c    6.0
d    7.0
dtype: float64

In [162]:
rs.index is df.index

True

In [164]:
rs.reindex_like(s) is df.index

False

In [166]:
s = pd.Series(np.random.randn(5), index=list("abcde"))
s1 = s[:4]
s2 = s[1:]
s1, s2

(a    0.526445
 b   -0.249722
 c    0.445011
 d   -1.166141
 dtype: float64,
 b   -0.249722
 c    0.445011
 d   -1.166141
 e    0.313851
 dtype: float64)

In [167]:
s1.align(s2)

(a    0.526445
 b   -0.249722
 c    0.445011
 d   -1.166141
 e         NaN
 dtype: float64,
 a         NaN
 b   -0.249722
 c    0.445011
 d   -1.166141
 e    0.313851
 dtype: float64)

In [168]:
s1.align(s2, join="inner")

(b   -0.249722
 c    0.445011
 d   -1.166141
 dtype: float64,
 b   -0.249722
 c    0.445011
 d   -1.166141
 dtype: float64)

In [171]:
s1.align(s2, join="left")

(a    0.526445
 b   -0.249722
 c    0.445011
 d   -1.166141
 dtype: float64,
 a         NaN
 b   -0.249722
 c    0.445011
 d   -1.166141
 dtype: float64)

In [176]:
rng = pd.date_range("1/3/2000", periods=8)
rng

DatetimeIndex(['2000-01-03', '2000-01-04', '2000-01-05', '2000-01-06',
               '2000-01-07', '2000-01-08', '2000-01-09', '2000-01-10'],
              dtype='datetime64[ns]', freq='D')

In [178]:
ts = pd.Series(np.random.randn(8), index=rng)
ts

2000-01-03    0.560080
2000-01-04   -1.588839
2000-01-05   -0.072549
2000-01-06   -0.087593
2000-01-07   -0.597083
2000-01-08    1.977064
2000-01-09   -1.571613
2000-01-10   -0.121199
Freq: D, dtype: float64

In [180]:
ts2 = ts.iloc[[0, 3, 6]]
ts2

2000-01-03    0.560080
2000-01-06   -0.087593
2000-01-09   -1.571613
Freq: 3D, dtype: float64

In [182]:
ts2.reindex(ts.index)

2000-01-03    0.560080
2000-01-04         NaN
2000-01-05         NaN
2000-01-06   -0.087593
2000-01-07         NaN
2000-01-08         NaN
2000-01-09   -1.571613
2000-01-10         NaN
Freq: D, dtype: float64

In [183]:
ts2.reindex(ts.index, method="ffill")

2000-01-03    0.560080
2000-01-04    0.560080
2000-01-05    0.560080
2000-01-06   -0.087593
2000-01-07   -0.087593
2000-01-08   -0.087593
2000-01-09   -1.571613
2000-01-10   -1.571613
Freq: D, dtype: float64

In [184]:
ts2.reindex(ts.index, method="bfill")

2000-01-03    0.560080
2000-01-04   -0.087593
2000-01-05   -0.087593
2000-01-06   -0.087593
2000-01-07   -1.571613
2000-01-08   -1.571613
2000-01-09   -1.571613
2000-01-10         NaN
Freq: D, dtype: float64

In [185]:
ts2.reindex(ts.index, method="nearest")

2000-01-03    0.560080
2000-01-04    0.560080
2000-01-05   -0.087593
2000-01-06   -0.087593
2000-01-07   -0.087593
2000-01-08   -1.571613
2000-01-09   -1.571613
2000-01-10   -1.571613
Freq: D, dtype: float64

In [186]:
ts2.reindex(ts.index, method="ffill", limit=1)

2000-01-03    0.560080
2000-01-04    0.560080
2000-01-05         NaN
2000-01-06   -0.087593
2000-01-07   -0.087593
2000-01-08         NaN
2000-01-09   -1.571613
2000-01-10   -1.571613
Freq: D, dtype: float64

In [190]:
ts2.reindex(ts.index, method="ffill", tolerance="1 day")

2000-01-03    0.560080
2000-01-04    0.560080
2000-01-05         NaN
2000-01-06   -0.087593
2000-01-07   -0.087593
2000-01-08         NaN
2000-01-09   -1.571613
2000-01-10   -1.571613
Freq: D, dtype: float64

In [191]:
ts2

2000-01-03    0.560080
2000-01-06   -0.087593
2000-01-09   -1.571613
Freq: 3D, dtype: float64

In [199]:
df

one       two     three
a  1.174030  0.678128       NaN
b -0.563444  0.571915 -0.533035
c -1.396908  0.687476  0.924228
d       NaN  0.580159  1.171627

In [201]:
df.drop(["two"], axis=1)

one     three
a  1.174030       NaN
b -0.563444 -0.533035
c -1.396908  0.924228
d       NaN  1.171627

In [202]:
df.drop(["c"], axis=0)

one       two     three
a  1.174030  0.678128       NaN
b -0.563444  0.571915 -0.533035
d       NaN  0.580159  1.171627

In [205]:
s

a    0.526445
b   -0.249722
c    0.445011
d   -1.166141
e    0.313851
dtype: float64

In [206]:
s.rename(str.upper)

A    0.526445
B   -0.249722
C    0.445011
D   -1.166141
E    0.313851
dtype: float64

In [219]:
df = pd.DataFrame(
    {"col1": np.random.randn(3), "col2": np.random.randn(3)}, index=["a", "b", "c"]
)

for col in df:
    print(col)

col1
col2


In [222]:
for label, content in df.items():
    print(label)
    print(content)

col1
a   -0.319334
b   -0.648431
c    0.642809
Name: col1, dtype: float64
col2
a   -0.522213
b    1.231661
c    0.489100
Name: col2, dtype: float64


In [231]:
for row_index, row in df.iterrows():
    print(row_index, row, sep="\n")

a
col1   -0.319334
col2   -0.522213
Name: a, dtype: float64
b
col1   -0.648431
col2    1.231661
Name: b, dtype: float64
c
col1    0.642809
col2    0.489100
Name: c, dtype: float64


In [233]:
df2 = pd.DataFrame({"x": [1, 2, 3], "y": [4, 5, 6]})
df2

x  y
0  1  4
1  2  5
2  3  6

In [234]:
df2.T

0  1  2
x  1  2  3
y  4  5  6

In [235]:
df2_t = pd.DataFrame({idx: values for idx, values in df2.iterrows()})
df2_t

0  1  2
x  1  2  3
y  4  5  6

In [236]:
for row in df.itertuples():
    print(row)

Pandas(Index='a', col1=-0.3193335369759607, col2=-0.5222125059877164)
Pandas(Index='b', col1=-0.6484314598576112, col2=1.2316609756472423)
Pandas(Index='c', col1=0.6428091268210046, col2=0.4890999564358188)


In [237]:
df

col1      col2
a -0.319334 -0.522213
b -0.648431  1.231661
c  0.642809  0.489100

In [238]:
s = pd.Series(pd.date_range("20130101 09:10:12", periods=4))
s

0   2013-01-01 09:10:12
1   2013-01-02 09:10:12
2   2013-01-03 09:10:12
3   2013-01-04 09:10:12
dtype: datetime64[ns]

In [239]:
s.dt.hour

0    9
1    9
2    9
3    9
dtype: int32

In [241]:
s.dt.second

0    12
1    12
2    12
3    12
dtype: int32

In [242]:
s[s.dt.day == 2]

1   2013-01-02 09:10:12
dtype: datetime64[ns]

In [250]:
stz = s.dt.tz_localize("US/Eastern")
stz

0   2013-01-01 09:10:12-05:00
1   2013-01-02 09:10:12-05:00
2   2013-01-03 09:10:12-05:00
3   2013-01-04 09:10:12-05:00
dtype: datetime64[ns, US/Eastern]

In [258]:
s = pd.Series(pd.timedelta_range("20130101", periods=4, freq="h"))
s

0   0 days 00:00:00.020130101
1   0 days 01:00:00.020130101
2   0 days 02:00:00.020130101
3   0 days 03:00:00.020130101
dtype: timedelta64[ns]

In [259]:
s.dt.components

days  hours  minutes  seconds  milliseconds  microseconds  nanoseconds
0     0      0        0        0            20           130          101
1     0      1        0        0            20           130          101
2     0      2        0        0            20           130          101
3     0      3        0        0            20           130          101

In [260]:
df1 = pd.DataFrame(
    {"one": [2, 1, 1, 1], "two": [1, 3, 2, 4], "three": [5, 4, 3, 2]}
)
df1[["one", "two", "three"]].sort_values(by=["one", "two"])

one  two  three
2    1    2      3
1    1    3      4
3    1    4      2
0    2    1      5

In [263]:
s[2] = np.nan
s.sort_values()

0   0 days 00:00:00.020130101
1   0 days 01:00:00.020130101
3   0 days 03:00:00.020130101
2                         NaT
dtype: timedelta64[ns]

In [264]:
s.sort_values(na_position="first")

2                         NaT
0   0 days 00:00:00.020130101
1   0 days 01:00:00.020130101
3   0 days 03:00:00.020130101
dtype: timedelta64[ns]

In [265]:
idx = pd.MultiIndex.from_tuples(
    [("a", 1), ("a", 2), ("a", 2), ("b", 2), ("b", 1), ("b", 1)]
    )

idx

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 2),
            ('b', 2),
            ('b', 1),
            ('b', 1)],
           )

In [267]:
idx.names = ["first", "second"]
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 2),
            ('b', 2),
            ('b', 1),
            ('b', 1)],
           names=['first', 'second'])

In [268]:
df_multi = pd.DataFrame({"A": np.arange(6, 0, -1)}, index=idx)
df_multi

A
first second   
a     1       6
      2       5
      2       4
b     2       3
      1       2
      1       1

In [269]:
df_multi.shape

(6, 1)

In [270]:
df_multi.sort_values(by=["second", "A"])

A
first second   
b     1       1
      1       2
a     1       6
b     2       3
a     2       4
      2       5

In [274]:
ser = pd.Series([1, 2, 3])
ser

0    1
1    2
2    3
dtype: int64

In [276]:
ser.searchsorted([1, 5])

array([0, 3])

In [279]:
ser.searchsorted([1, 1000], side='right')

array([1, 3])

In [284]:
s = pd.Series(np.random.permutation(10))
s

0    4
1    6
2    8
3    3
4    2
5    7
6    0
7    1
8    5
9    9
dtype: int64

In [285]:
s.sort_values()

6    0
7    1
4    2
3    3
0    4
8    5
1    6
5    7
2    8
9    9
dtype: int64

In [286]:
s.nsmallest(3)

6    0
7    1
4    2
dtype: int64

In [287]:
s.nlargest(3)

9    9
2    8
5    7
dtype: int64

In [294]:
dft = pd.DataFrame(
    {
        "A": np.random.rand(3),
        "B": 1,
        "C": "foo",
        "D": pd.Timestamp("20010102"),
        "E": pd.Series([1.0] * 3).astype("float32"),
        "F": False,
        "G": pd.Series([1] * 3, dtype="int8"),
    }
)

dft.dtypes

A          float64
B            int64
C           object
D    datetime64[s]
E          float32
F             bool
G             int8
dtype: object

In [295]:
dft.dtypes.value_counts()

float64          1
int64            1
object           1
datetime64[s]    1
float32          1
bool             1
int8             1
Name: count, dtype: int64

In [296]:
dft = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]})
dft

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [297]:
dft.loc[:, ["a", "b"]]

a  b
0  1  4
1  2  5
2  3  6

In [298]:
dft.loc[:, ["a", "b"]].astype(np.uint8).dtypes

a    uint8
b    uint8
dtype: object

In [299]:
import datetime

df = pd.DataFrame(
    [
        [1, 2],
        ["a", "b"],
        [datetime.datetime(2016, 3, 2), datetime.datetime(2016, 3, 2)]
    ]
)

df = df.T
df

0  1                    2
0  1  a  2016-03-02 00:00:00
1  2  b  2016-03-02 00:00:00

In [300]:
df.dtypes

0    object
1    object
2    object
dtype: object

In [302]:
df.infer_objects().dtypes

0             int64
1            object
2    datetime64[ns]
dtype: object

In [304]:
m = ["1.1", 2, 3]
pd.to_numeric(m)

array([1.1, 2. , 3. ])

In [309]:
import datetime

m = ["2016-07-09", datetime.datetime(2016, 3, 2)]

pd.to_datetime(m)

DatetimeIndex(['2016-07-09', '2016-03-02'], dtype='datetime64[ns]', freq=None)

In [311]:
pd.to_datetime(m).dtype

dtype('<M8[ns]')

In [312]:
m = ["5us", pd.Timedelta("1day")]

pd.to_timedelta(m)

TimedeltaIndex(['0 days 00:00:00.000005', '1 days 00:00:00'], dtype='timedelta64[ns]', freq=None)

In [313]:
import datetime

m = ["apple", datetime.datetime(2016, 3, 2)]

pd.to_datetime(m, errors="coerce")

/tmp/ipykernel_1334/2710552240.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(m, errors="coerce")


DatetimeIndex(['NaT', '2016-03-02'], dtype='datetime64[ns]', freq=None)

In [314]:
pd.to_numeric(m, errors="coerce")

array([nan, nan])

In [316]:
m = ["apple", pd.Timedelta("1day")]

pd.to_timedelta(m, errors="coerce")

TimedeltaIndex([NaT, '1 days'], dtype='timedelta64[ns]', freq=None)

In [317]:
m = ["1", 2, 3]
pd.to_numeric(m, downcast="integer")

array([1, 2, 3], dtype=int8)

In [318]:
pd.to_numeric(m, downcast="signed")

array([1, 2, 3], dtype=int8)

In [319]:
pd.to_numeric(m, downcast="float")

array([1., 2., 3.], dtype=float32)

In [321]:
import datetime

df = pd.DataFrame([["2016-07-09", datetime.datetime(2016, 3, 2)]] * 2, dtype="O")
df.dtypes

0    object
1    object
dtype: object

In [323]:
def subdtypes(dtype):
    subs = dtype.__subclasses__()
    if not subs:
        return dtype
    return [dtype, [subdtypes(dt) for dt in subs]]

In [324]:
subdtypes(np.generic)

[numpy.generic,
 [[numpy.number,
   [[numpy.integer,
     [[numpy.signedinteger,
       [numpy.int8,
        numpy.int16,
        numpy.int32,
        numpy.int64,
        numpy.longlong,
        numpy.timedelta64]],
      [numpy.unsignedinteger,
       [numpy.uint8,
        numpy.uint16,
        numpy.uint32,
        numpy.uint64,
        numpy.ulonglong]]]],
    [numpy.inexact,
     [[numpy.floating,
       [numpy.float16, numpy.float32, numpy.float64, numpy.longdouble]],
      [numpy.complexfloating,
       [numpy.complex64, numpy.complex128, numpy.clongdouble]]]]]],
  [numpy.flexible,
   [[numpy.character, [numpy.bytes_, numpy.str_]],
    [numpy.void, [numpy.record]]]],
  numpy.bool_,
  numpy.datetime64,
  numpy.object_]]