In [1]:
import numpy as np

In [2]:
a = np.array([3, 5, 2], dtype=np.uint32)
b = np.array([2, 4, 1], dtype=np.int32)

c = a - b

print(c.dtype, c)

int64 [1 1 1]


In [3]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [4]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [8]:
np.diag(np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [11]:
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [14]:
np.vander([1, 2, 3], 2)

array([[1, 1],
       [2, 1],
       [3, 1]])

In [15]:
np.vander([1, 2, 3], 3)

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

In [20]:
np.zeros((3, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])