In [1]:
import numpy as np

In [2]:
from numpy.random import default_rng
default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [3]:
default_rng(42).random((2, 3, 2))

array([[[0.77395605, 0.43887844],
        [0.85859792, 0.69736803],
        [0.09417735, 0.97562235]],

       [[0.7611397 , 0.78606431],
        [0.12811363, 0.45038594],
        [0.37079802, 0.92676499]]])

In [4]:
a = np.indices((3, 3))
a, a.shape

(array([[[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],
 
        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]]),
 (2, 3, 3))

In [5]:
a = np.array((1, 2, 3, 4))
b = a[:2].copy()
b += 1
type(a), type(b)

(numpy.ndarray, numpy.ndarray)

In [6]:
c = np.diag((-3, -4))
c

array([[-3,  0],
       [ 0, -4]])

In [11]:
np.genfromtxt('Iris.csv', delimiter=',', dtype=None, encoding='utf-8', names=True, usecols=(0, 1, 2, 3, 4))

array([(  1, 5.1, 3.5, 1.4, 0.2), (  2, 4.9, 3. , 1.4, 0.2),
       (  3, 4.7, 3.2, 1.3, 0.2), (  4, 4.6, 3.1, 1.5, 0.2),
       (  5, 5. , 3.6, 1.4, 0.2), (  6, 5.4, 3.9, 1.7, 0.4),
       (  7, 4.6, 3.4, 1.4, 0.3), (  8, 5. , 3.4, 1.5, 0.2),
       (  9, 4.4, 2.9, 1.4, 0.2), ( 10, 4.9, 3.1, 1.5, 0.1),
       ( 11, 5.4, 3.7, 1.5, 0.2), ( 12, 4.8, 3.4, 1.6, 0.2),
       ( 13, 4.8, 3. , 1.4, 0.1), ( 14, 4.3, 3. , 1.1, 0.1),
       ( 15, 5.8, 4. , 1.2, 0.2), ( 16, 5.7, 4.4, 1.5, 0.4),
       ( 17, 5.4, 3.9, 1.3, 0.4), ( 18, 5.1, 3.5, 1.4, 0.3),
       ( 19, 5.7, 3.8, 1.7, 0.3), ( 20, 5.1, 3.8, 1.5, 0.3),
       ( 21, 5.4, 3.4, 1.7, 0.2), ( 22, 5.1, 3.7, 1.5, 0.4),
       ( 23, 4.6, 3.6, 1. , 0.2), ( 24, 5.1, 3.3, 1.7, 0.5),
       ( 25, 4.8, 3.4, 1.9, 0.2), ( 26, 5. , 3. , 1.6, 0.2),
       ( 27, 5. , 3.4, 1.6, 0.4), ( 28, 5.2, 3.5, 1.5, 0.2),
       ( 29, 5.2, 3.4, 1.4, 0.2), ( 30, 4.7, 3.2, 1.6, 0.2),
       ( 31, 4.8, 3.1, 1.6, 0.2), ( 32, 5.4, 3.4, 1.5, 0.4),
       ( 33, 5.2, 4.1, 1