In [1]:
import numpy as np

In [12]:
matrix = np.arange(25, dtype=np.double).reshape(5, 5)
complex_matrix = matrix.view(dtype=np.complex64)
complex_matrix

array([[0.+0.j      , 0.+1.875j   , 0.+2.j      , 0.+2.125j   ,
        0.+2.25j    ],
       [0.+2.3125j  , 0.+2.375j   , 0.+2.4375j  , 0.+2.5j     ,
        0.+2.53125j ],
       [0.+2.5625j  , 0.+2.59375j , 0.+2.625j   , 0.+2.65625j ,
        0.+2.6875j  ],
       [0.+2.71875j , 0.+2.75j    , 0.+2.765625j, 0.+2.78125j ,
        0.+2.796875j],
       [0.+2.8125j  , 0.+2.828125j, 0.+2.84375j , 0.+2.859375j,
        0.+2.875j   ]], dtype=complex64)

In [22]:
x = np.array([(1, 2)], dtype=[('a', np.int8), ('b', np.int8)])
y = x.view(dtype=np.int16, type=np.matrix)
x, y, type(y)

(array([(1, 2)], dtype=[('a', 'i1'), ('b', 'i1')]),
 matrix([[513]], dtype=int16),
 numpy.matrix)

In [30]:
x = np.arange(9).reshape(3, 3)
y = x[[1, 2]]  # copying
x, y

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[3, 4, 5],
        [6, 7, 8]]))

In [31]:
x[[1, 2]] = [[10, 11, 12], 
             [13, 14, 15]]
x

array([[ 0,  1,  2],
       [10, 11, 12],
       [13, 14, 15]])

In [33]:
x = np.ones((2, 3))
y = x.T  # makes the array non-contiguous
y

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
z = y.view()
z.shape

(3, 2)

In [42]:
# z.shape = 6
z.ravel(), z.ravel().shape  # contigous flatten array

(array([1., 1., 1., 1., 1., 1.]), (6,))

In [47]:
z.reshape(-1), z.reshape(-1).shape

(array([1., 1., 1., 1., 1., 1.]), (6,))

In [51]:
x = np.arange(9)
y = x.reshape(3, 3)
y.base  # .reshape() creates a view

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
z = y[[2, 1]]
z

array([[6, 7, 8],
       [3, 4, 5]])

In [55]:
z.base is None  # advanced indexing creates a copy

True

In [57]:
x = np.array([1, 2, 3, 4])
x.base is None

True

In [60]:
y = x[2:]
y.base is x

True

In [61]:
y.base is None

False

In [70]:
y = x.reshape(2, 2)  # view x
y.base is x, y 

(True,
 array([[1, 2],
        [3, 4]]))

In [71]:
y = x[[0, 1]]  # copy from x
y.base is x

False