In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x[2]

2

In [3]:
x.shape = (2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
x[1, 3]

8

In [5]:
x[0, 2] == x[0][2]

True

In [6]:
x = np.arange(0, 8)
x, x[-2:]

(array([0, 1, 2, 3, 4, 5, 6, 7]), array([6, 7]))

In [7]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x, x.shape

(array([[[1],
         [2],
         [3]],
 
        [[4],
         [5],
         [6]]]),
 (2, 3, 1))

In [8]:
x[..., 0] == x[:, :, 0], x[..., 0]

(array([[ True,  True,  True],
        [ True,  True,  True]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [9]:
x[:, np.newaxis, :, :].shape

(2, 1, 3, 1)

In [10]:
x[:, None, :, :].shape

(2, 1, 3, 1)

In [11]:
x = np.arange(5)
x[:, np.newaxis] + x[np.newaxis, :]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [12]:
x = np.arange(start=10, stop=1, step=-1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [13]:
x[np.array([7, 8, 1, 0])]

array([ 3,  2,  9, 10])

In [14]:
y = np.arange(35).reshape(5, 7)
y.shape, y

((5, 7),
 array([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34]]))

In [15]:
y[np.array([0, 2, 4]), np.array([0, 1, 2])] # [[0,0], [2, 1], [4, 2]]

array([ 0, 15, 30])

In [16]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [17]:
y[np.array([0, 2, 4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [18]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x, x.shape

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 (3, 2))

In [19]:
x[[0, 1, 2], [0, 1, 0]]  # (0, 0) (1, 1), (2, 0)

array([1, 4, 5])

In [20]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])

rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)

columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)

x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

In [21]:
rows = np.array([0, 3], dtype=np.intp)
columns = np.array([0, 2], dtype=np.intp)
x[np.ix_(rows, columns)], rows, columns

(array([[ 0,  2],
        [ 9, 11]]),
 array([0, 3]),
 array([0, 2]))

In [22]:
a = np.arange(10).reshape(2, 5)
ixgrid = np.ix_([0, 1], [2, 4])
ixgrid, ixgrid[0].shape, ixgrid[1].shape

((array([[0],
         [1]]),
  array([[2, 4]])),
 (2, 1),
 (1, 2))

In [23]:
x, rows, columns

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([0, 3]),
 array([0, 2]))

In [24]:
x[rows, columns]

array([ 0, 11])

In [25]:
x = np.array([[1., 2.], [np.nan, 3], [np.nan, np.nan]])
x

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

In [26]:
x[~np.isnan(x)], x[np.isnan(x)]

(array([1., 2., 3.]), array([nan, nan, nan]))

In [27]:
x = np.arange(35).reshape(5, 7)
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [28]:
b = x > 20
b[:, 5]

array([False, False, False,  True,  True])

In [29]:
x = np.array([[0, 1], [1, 1], [2, 2]])
rowsum = x.sum(1)
rowsum

array([1, 2, 4])

In [30]:
x[rowsum <= 2, :]

array([[0, 1],
       [1, 1]])

In [31]:
x = np.arange(12).reshape(4, 3)
rows = (x.sum(-1) % 2) == 0
rows, x, x.sum(-1)

(array([False,  True, False,  True]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([ 3, 12, 21, 30]))

In [32]:
columns = [0, 2]
x[np.ix_(rows, columns)]

array([[ 3,  5],
       [ 9, 11]])

In [33]:
x = np.arange(16).reshape(4, 4) + 1
rows = [0, 2]
columns = [0, 2]
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
ix = np.ix_(rows, columns)  # [[(0, 0), (0, 2)], [[2, 0], [2, 2]]
ix, ix[0].shape, ix[1].shape

((array([[0],
         [2]]),
  array([[0, 2]])),
 (2, 1),
 (1, 2))

In [35]:
x[ix]

array([[ 1,  3],
       [ 9, 11]])

In [36]:
rows

[0, 2]

In [37]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = (x.sum(-1) % 2) == 0
columns = [0, 2]
rows

array([False,  True, False,  True])

In [38]:
rows = rows.nonzero()[0]
rows

array([1, 3])

In [39]:
x[rows[:, np.newaxis], columns]

array([[ 3,  5],
       [ 9, 11]])

In [40]:
rows, columns, x

(array([1, 3]),
 [0, 2],
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [41]:
y = np.arange(35).reshape(5, 7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [42]:
y[np.array([0, 2, 4]), 1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [43]:
y[:, 1:3][np.array([0, 2, 4]), :]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [44]:
x = np.arange(35).reshape(5, 7)
b = x > 20
b, x

(array([[False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [ True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True]]),
 array([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34]]))

In [45]:
x[b[:, 5], 1:3]

array([[22, 23],
       [29, 30]])

In [46]:
x = np.zeros((2, 2), dtype=[('a', np.int32), ('b', np.float64, (3, 3))])
x.shape 

(2, 2)

In [50]:
x['a'].shape, x['b'].shape, x['a'].dtype

((2, 2), (2, 2, 3, 3), dtype('int32'))

In [48]:
x['a']

array([[0, 0],
       [0, 0]], dtype=int32)

In [49]:
x['b']

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [56]:
x[1] = 1.2
x

array([[(0, [[0. , 0. , 0. ], [0. , 0. , 0. ], [0. , 0. , 0. ]]),
        (0, [[0. , 0. , 0. ], [0. , 0. , 0. ], [0. , 0. , 0. ]])],
       [(1, [[1.2, 1.2, 1.2], [1.2, 1.2, 1.2], [1.2, 1.2, 1.2]]),
        (1, [[1.2, 1.2, 1.2], [1.2, 1.2, 1.2], [1.2, 1.2, 1.2]])]],
      dtype=[('a', '<i4'), ('b', '<f8', (3, 3))])

In [57]:
x = np.arange(0, 50, 10)
x

array([ 0, 10, 20, 30, 40])

In [58]:
x[np.array([1, 1, 1, 1])] += 1  # value of the array at x[1] + 1 is asigned to x[1] three times
x

array([ 0, 11, 20, 30, 40])

In [60]:
z = np.arange(81).reshape(3, 3, 3, 3)
indices = (1, 1, 1, 1)
z[indices]


40

In [61]:
indices = (1, 1, 1, slice(0, 2)) # same as [1, 1, 1, 0:2]
z[indices]

array([39, 40])

In [70]:
indices = (1, Ellipsis, 1)  # Same as [1, ..., 1]
z[indices]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

In [76]:
z[1] == z[[1, 1, 1, 1]]

array([[[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]],


       [[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]],


       [[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]]],


       [[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ Tru

In [77]:
z[(1, 1, 1, 1)]

40

In [78]:
x == x[...]

array([ True,  True,  True,  True,  True])

In [79]:
x[Ellipsis] == x[...]

array([ True,  True,  True,  True,  True])