In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int64'

In [6]:
a.itemsize

8

In [7]:
type(a)

numpy.ndarray

In [8]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [9]:
type(b)

numpy.ndarray

In [10]:
a = np.array([np.pi, np.exp(1)])
a, type(a), a.ndim

(array([3.14159265, 2.71828183]), numpy.ndarray, 1)

In [11]:
a = np.array([(2, 3, 4), (1 + 2j, 2 + 3j, 3 + 2j)])
a.imag, type(a[1])

(array([[0., 0., 0.],
        [2., 3., 2.]]),
 numpy.ndarray)

In [12]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [13]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.empty((2, 3))

array([[0., 0., 0.],
       [2., 3., 2.]])

In [16]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [17]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [18]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [19]:
np.linspace(0, 2, 10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [20]:
np.linspace(0, 2 * np.pi, 30)

array([0.        , 0.21666156, 0.43332312, 0.64998469, 0.86664625,
       1.08330781, 1.29996937, 1.51663094, 1.7332925 , 1.94995406,
       2.16661562, 2.38327719, 2.59993875, 2.81660031, 3.03326187,
       3.24992343, 3.466585  , 3.68324656, 3.89990812, 4.11656968,
       4.33323125, 4.54989281, 4.76655437, 4.98321593, 5.1998775 ,
       5.41653906, 5.63320062, 5.84986218, 6.06652374, 6.28318531])

In [21]:
np.sin(np.linspace(0, 2 * np.pi, 30))

array([ 0.00000000e+00,  2.14970440e-01,  4.19889102e-01,  6.05174215e-01,
        7.62162055e-01,  8.83512044e-01,  9.63549993e-01,  9.98533414e-01,
        9.86826523e-01,  9.28976720e-01,  8.27688998e-01,  6.87699459e-01,
        5.15553857e-01,  3.19301530e-01,  1.08119018e-01, -1.08119018e-01,
       -3.19301530e-01, -5.15553857e-01, -6.87699459e-01, -8.27688998e-01,
       -9.28976720e-01, -9.86826523e-01, -9.98533414e-01, -9.63549993e-01,
       -8.83512044e-01, -7.62162055e-01, -6.05174215e-01, -4.19889102e-01,
       -2.14970440e-01, -2.44929360e-16])

In [22]:
one_d = np.arange(6)
two_d = np.arange(12).reshape(4, 3)
three_d = np.arange(36).reshape(6, 2, 3)
print(one_d)
print(two_d)
print(three_d)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]]]


In [23]:
import sys
np.set_printoptions(threshold=sys.maxsize)

In [24]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
a, b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [25]:
a - b

array([20, 29, 38, 47])

In [26]:
b**2

array([0, 1, 4, 9])

In [27]:
10 * np.sin(b)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [28]:
b *= 2
b, b > 4

(array([0, 2, 4, 6]), array([False, False, False,  True]))

In [29]:
A = np.array([[0, 1],
             [1, 1]])
B = np.array([[2, 0],
             [3, 4]])

A * B # elementwise product

array([[0, 0],
       [3, 4]])

In [30]:
A @ B # matrix product

array([[3, 4],
       [5, 4]])

In [31]:
A.dot(B) # matrix product

array([[3, 4],
       [5, 4]])

In [32]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)
c = a + b
d = np.exp(c * 1j)
d, d.dtype.name

(array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
        -0.54030231-0.84147098j]),
 'complex128')

In [33]:
b = np.arange(12).reshape(4, 3)
b, b.shape

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 (4, 3))

In [34]:
b.sum(axis=0), b.sum(axis=1)

(array([18, 22, 26]), array([ 3, 12, 21, 30]))

In [35]:
np.trace(np.eye(3))

3.0

In [36]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
np.trace(a)

6

In [38]:
a[:6:2] = 1000 # from start to position 6, exlusive, set every 2nd elemnt to 1000
a

array([[1000, 1000, 1000, 1000, 1000],
       [   5,    6,    7,    8,    9]])

In [39]:
a[2:5] = 1000
a

array([[1000, 1000, 1000, 1000, 1000],
       [   5,    6,    7,    8,    9]])

In [40]:
a[::-1] # reserved a

array([[   5,    6,    7,    8,    9],
       [1000, 1000, 1000, 1000, 1000]])

In [41]:
def f(x, y):
    return 10 * x * y

b = np.fromfunction(f, (5, 4), dtype=np.int8)
b

array([[  0,   0,   0,   0],
       [  0,  10,  20,  30],
       [  0,  20,  40,  60],
       [  0,  30,  60,  90],
       [  0,  40,  80, 120]], dtype=int8)

In [42]:
b[-1], b[-1, :], b[-1, ...]

(array([  0,  40,  80, 120], dtype=int8),
 array([  0,  40,  80, 120], dtype=int8),
 array([  0,  40,  80, 120], dtype=int8))

In [43]:
c = np.arange(100).reshape(5, 2, 10)
c

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [44]:
c.shape

(5, 2, 10)

In [45]:
c[0, ...]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [46]:
c[0, :, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [47]:
c = np.arange(27).reshape(3, 3, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [48]:
for element in c:
    print(element)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [49]:
for element in c.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [50]:
c.shape

(3, 3, 3)

In [51]:
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [52]:
c = np.arange(16).reshape(4, 4)
c, c.T

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]]))

In [53]:
c = np.arange(16).reshape(4, -1)
c, c.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 (4, 4))

In [54]:
d = np.resize(c, (8, 1))
d.shape

(8, 1)

In [55]:
np.hstack(d), d[::2], d[::3]

(array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([[0],
        [2],
        [4],
        [6]]),
 array([[0],
        [3],
        [6]]))

In [56]:
rgn = np.random.default_rng(42)
print(rgn)

Generator(PCG64)


In [57]:
a = np.array([[4, 2],
              [2, 4]])
b = np.array([[4, 2],
              [2, 4]])
np.column_stack((a, b)), np.row_stack((a, b))


(array([[4, 2, 4, 2],
        [2, 4, 2, 4]]),
 array([[4, 2],
        [2, 4],
        [4, 2],
        [2, 4]]))

In [58]:
a.shape, a[:, np.newaxis, np.newaxis, ...].shape

((2, 2), (2, 1, 1, 2))

In [59]:
# np.array[1:4, 0, 4] ERROR
np.r_[1:4, 0, 4] # slicing and concatenation along the first axis

array([1, 2, 3, 0, 4])

In [60]:
np.c_[0:6:2, np.array([1, 2, 3])] # slicing and concatenation alon the second axis

array([[0, 1],
       [2, 2],
       [4, 3]])

In [61]:
a = np.floor(10 * rg.random((2, 2)))
b = np.floor(10 * rg.random((2, 2)))

a, b

NameError: name 'rg' is not defined

In [ ]:
np.vstack((a, b))

array([[6., 5.],
       [5., 3.],
       [0., 4.],
       [2., 4.]])

In [ ]:
# hstack stacks along their second axes and vstack along their first axes
np.hstack((a, b)), np.vstack((a, b))

(array([[6., 5., 0., 4.],
        [5., 3., 2., 4.]]),
 array([[6., 5.],
        [5., 3.],
        [0., 4.],
        [2., 4.]]))

In [ ]:
np.column_stack is np.hstack

False

In [ ]:
np.row_stack is np.vstack

True

In [ ]:
a = np.floor(10 * rg.random((2, 12)))
a, a.shape

(array([[3., 0., 1., 9., 9., 6., 2., 9., 7., 7., 4., 2.],
        [0., 9., 4., 2., 3., 5., 1., 8., 7., 7., 4., 6.]]),
 (2, 12))

In [ ]:
np.hsplit(a, 3) # equivalent np.split(a, 3, axes=1)

[array([[3., 0., 1., 9.],
        [0., 9., 4., 2.]]),
 array([[9., 6., 2., 9.],
        [3., 5., 1., 8.]]),
 array([[7., 7., 4., 2.],
        [7., 7., 4., 6.]])]

In [ ]:
np.vsplit(np.hsplit(a, 3)[0], 2) # equivalent np.split(a, 3, axes=0)

[array([[3., 0., 1., 9.]]), array([[0., 9., 4., 2.]])]

In [ ]:
c = a.view()
a, c

(array([[3., 0., 1., 9., 9., 6., 2., 9., 7., 7., 4., 2.],
        [0., 9., 4., 2., 3., 5., 1., 8., 7., 7., 4., 6.]]),
 array([[3., 0., 1., 9., 9., 6., 2., 9., 7., 7., 4., 2.],
        [0., 9., 4., 2., 3., 5., 1., 8., 7., 7., 4., 6.]]))

In [ ]:
a is c

False

In [ ]:
a.base is c

False

In [ ]:
c.base is a # c is a view of the data owned by a

True

In [ ]:
c = np.resize(c, (2, 6))
c, c.shape

(array([[3., 0., 1., 9., 9., 6.],
        [2., 9., 7., 7., 4., 2.]]),
 (2, 6))

In [ ]:
a

array([[3., 0., 1., 9., 9., 6., 2., 9., 7., 7., 4., 2.],
       [0., 9., 4., 2., 3., 5., 1., 8., 7., 7., 4., 6.]])

In [ ]:
a.shape

(2, 12)

In [ ]:
a[:, 1:3]

array([[0., 1.],
       [9., 4.]])