In [1]:
import numpy as np

In [2]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
x, x.shape

(array([('Rex', 9, 81.), ('Fido', 3, 27.)],
       dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')]),
 (2,))

In [3]:
x[0], x[1]

(('Rex', 9, 81.), ('Fido', 3, 27.))

In [4]:
x['age']

array([9, 3], dtype=int32)

In [5]:
x['name']

array(['Rex', 'Fido'], dtype='<U10')

In [6]:
np.dtype('i8, f4, S3')

dtype([('f0', '<i8'), ('f1', '<f4'), ('f2', 'S3')])

In [7]:
np.dtype('3int8, float32, (2, 3)float64')

dtype([('f0', 'i1', (3,)), ('f1', '<f4'), ('f2', '<f8', (2, 3))])

In [11]:
np.dtype({'names': ['col1', 'col2'], 'formats': ['i4', 'f4']})

dtype([('col1', '<i4'), ('col2', '<f4')])

In [12]:
np.dtype({'names': ['col1', 'col2'],
          'formats': ['i4', 'f4'],
          'offsets': [0, 4],
          'itemsize': 12})

dtype({'names': ['col1', 'col2'], 'formats': ['<i4', '<f4'], 'offsets': [0, 4], 'itemsize': 12})

In [13]:
np.dtype({'col1': ('i1', 0), 'col2': ('f4', 1)})

dtype([('col1', 'i1'), ('col2', '<f4')])

In [31]:
d = np.dtype([('x', 'i1'), ('y', 'f4'), ('z', '<datetime64'), ('a', 'c16'), ('b', 'c8')])
d.names, d.type, d['x'], d['z'], d['a']

(('x', 'y', 'z', 'a', 'b'),
 numpy.void,
 dtype('int8'),
 dtype('<M8'),
 dtype('complex128'))

In [32]:
d.fields

mappingproxy({'x': (dtype('int8'), 0),
              'y': (dtype('float32'), 1),
              'z': (dtype('<M8'), 5),
              'a': (dtype('complex128'), 13),
              'b': (dtype('complex64'), 29)})

In [33]:
def print_offsets(d):
    print("offsets:", [d.fields[name][1] for name in d.names])
    print("itemsize:", d.itemsize)
print_offsets(d)

offsets: [0, 1, 5, 13, 29]
itemsize: 37


In [40]:
print_offsets(np.dtype('u1, u1, i4, u1, i8, u2', align=True))

offsets: [0, 1, 4, 8, 16, 24]
itemsize: 32


In [41]:
np.dtype([(('my name', 'my'), 'f4')])

dtype([(('my name', 'my'), '<f4')])

In [55]:
d = np.dtype({'name': ('i4', 0, 'my name'), "surname": ('i8', 0, 'my surname')})
d

dtype({'names': ['name', 'surname'], 'formats': ['<i4', '<i8'], 'offsets': [0, 0], 'titles': ['my name', 'my surname'], 'itemsize': 8})

In [56]:
d.name, d['name'], d.fields

('void64',
 dtype('int32'),
 mappingproxy({'name': (dtype('int32'), 0, 'my name'),
               'my name': (dtype('int32'), 0, 'my name'),
               'surname': (dtype('int64'), 0, 'my surname'),
               'my surname': (dtype('int64'), 0, 'my surname')}))

In [57]:
for name in d.names:
    print(d.fields[name][:2])

(dtype('int32'), 0)
(dtype('int64'), 0)


In [60]:
x = np.array([(1, 2, 3), (4, 5, 6)], dtype='i8, f4, f8')
x[1] = (7, 8, 9)
x

array([(1, 2., 3.), (7, 8., 9.)],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '<f8')])

In [62]:
x = np.zeros(2, dtype='i8, f4, ?, S1')
x[:] = 3
x

array([(3, 3.,  True, b'3'), (3, 3.,  True, b'3')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [66]:
x[:] = np.arange(2)
x

array([(0, 0., False, b'0'), (1, 1.,  True, b'1')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [70]:
twofield = np.zeros(2, dtype=[('A', 'i4'), ('B', 'i4')])
onefield = np.zeros(2, dtype=[('A', 'i4')])
nostruct = np.zeros(2, dtype='i4')
nostruct, onefield, twofield

(array([0, 0], dtype=int32),
 array([(0,), (0,)], dtype=[('A', '<i4')]),
 array([(0, 0), (0, 0)], dtype=[('A', '<i4'), ('B', '<i4')]))

In [71]:
nostruct[:] = onefield
nostruct

array([0, 0], dtype=int32)

In [72]:
a = np.zeros(3, dtype=[('a', 'i8'), ('b', 'f4'), ('c', 'S3')])
b = np.ones(3, dtype=[('x', 'f4'), ('y', 'S3'), ('z', 'O')])
a, b

(array([(0, 0., b''), (0, 0., b''), (0, 0., b'')],
       dtype=[('a', '<i8'), ('b', '<f4'), ('c', 'S3')]),
 array([(1., b'1', 1), (1., b'1', 1), (1., b'1', 1)],
       dtype=[('x', '<f4'), ('y', 'S3'), ('z', 'O')]))

In [73]:
b[:] = a
b

array([(0., b'0.0', b''), (0., b'0.0', b''), (0., b'0.0', b'')],
      dtype=[('x', '<f4'), ('y', 'S3'), ('z', 'O')])

In [78]:
x = np.array([(1, 2), (3, 4)], dtype=[('foo', 'i8'), ('bar', 'f4')])
x['foo'], type(x['foo'])

(array([1, 3]), numpy.ndarray)

In [77]:
x['bar']

array([2., 4.], dtype=float32)

In [79]:
x['foo'] = 10
x

array([(10, 2.), (10, 4.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [82]:
y = x['bar']
y[:] = np.exp(1)
x

array([(10, 2.7182817), (10, 2.7182817)],
      dtype=[('foo', '<i8'), ('bar', '<f4')])

In [83]:
x = np.zeros((2, 2), dtype=[('a', np.int32), ('b', np.float64, (3, 3))])
x['a'].shape

(2, 2)

In [85]:
x

array([[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
       [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]],
      dtype=[('a', '<i4'), ('b', '<f8', (3, 3))])

In [87]:
x['b'].shape

(2, 2, 3, 3)

In [93]:
a = np.zeros(3, dtype=[('a', 'i4'), ('b', 'i4'), ('c', 'f4')])
a, a.shape

(array([(0, 0, 0.), (0, 0, 0.), (0, 0, 0.)],
       dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<f4')]),
 (3,))

In [94]:
a['a'], a['a'].shape

(array([0, 0, 0], dtype=int32), (3,))

In [96]:
a[['a']], a[['a']].shape

(array([(0,), (0,), (0,)],
       dtype={'names': ['a'], 'formats': ['<i4'], 'offsets': [0], 'itemsize': 12}),
 (3,))

In [99]:
a[['a', 'c']], a[['a', 'c']].shape

(array([(0, 0.), (0, 0.), (0, 0.)],
       dtype={'names': ['a', 'c'], 'formats': ['<i4', '<f4'], 'offsets': [0, 8], 'itemsize': 12}),
 (3,))

In [104]:
a[['b']]

array([(0,), (0,), (0,)],
      dtype={'names': ['b'], 'formats': ['<i4'], 'offsets': [4], 'itemsize': 12})

In [106]:
# a[['a', 'c']].view('i8')  # ValueError

In [108]:
from numpy.lib.recfunctions import repack_fields
repack_fields(a[['a', 'c']]).view('i8')

array([0, 0, 0])

In [115]:
b = np.zeros(3, dtype=[('x', 'f4'), ('y', 'f4'), ('z', 'f4')])
b[['x', 'z']].view('i4'), b['x'].view('i4')

(array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([0, 0, 0], dtype=int32))

In [118]:
from numpy.lib.recfunctions import structured_to_unstructured
structured_to_unstructured(b[['x', 'z']])

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [123]:
a[['a', 'c']] = (2, 3)
a

array([(2, 0, 3.), (2, 0, 3.), (2, 0, 3.)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<f4')])

In [124]:
a[['a', 'c']] = a[['c', 'a']]
a

array([(3, 0, 2.), (3, 0, 2.), (3, 0, 2.)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<f4')])

In [129]:
x = np.array([1., 2., 3.], dtype='i1, f4, f8')
scalar = x[0]
scalar, x

((1, 1., 1.),
 array([(1, 1., 1.), (2, 2., 2.), (3, 3., 3.)],
       dtype=[('f0', 'i1'), ('f1', '<f4'), ('f2', '<f8')]))

In [130]:
type(scalar)

numpy.void

In [133]:
x = np.array([(1, 2), (3, 4)], dtype=[('foo', 'i1'), ('bar', 'f4')])
s = x[1]
s['bar'] = np.exp(1)
x

array([(1, 2.       ), (3, 2.7182817)],
      dtype=[('foo', 'i1'), ('bar', '<f4')])

In [139]:
scalar = np.array([(1, 2., 3.)], dtype='i, f, f')[0]
scalar[0], scalar[0].dtype, type(scalar)

(1, dtype('int32'), numpy.void)

In [140]:
scalar.item(), type(scalar.item())

((1, 2.0, 3.0), tuple)

In [144]:
a = np.array([(1, 2), (2, 2)], dtype=[('a', 'i4'), ('b', 'i4')])
b = np.array([(1, 2), (2, 2)], dtype=[('a', 'f4'), ('b', 'f4')])
c = np.array([(1, 2), (2, 3)], dtype=[('a', 'i4'), ('b', 'i4')])
a == b, a == c

(array([ True,  True]), array([ True, False]))

In [145]:
np.result_type(np.dtype("i, >i"))

dtype([('f0', '<i4'), ('f1', '<i4')])

In [147]:
np.result_type(np.dtype("i, i"), np.dtype("i, >i"))

dtype([('f0', '<i4'), ('f1', '<i4')])

In [148]:
dt = np.dtype("i1, V3, i4, V1")[["f0", "f2"]]
dt

dtype({'names': ['f0', 'f2'], 'formats': ['i1', '<i4'], 'offsets': [0, 4], 'itemsize': 9})

In [149]:
np.result_type(dt)

dtype([('f0', 'i1'), ('f2', '<i4')])

In [161]:
dt = np.dtype("i1, V8, i4, V1", align=True)[["f0", "f2"]]  # `V3` 3 bytes of padding
dt

dtype({'names': ['f0', 'f2'], 'formats': ['i1', '<i4'], 'offsets': [0, 12], 'itemsize': 20}, align=True)

In [151]:
np.result_type(dt)

dtype([('f0', 'i1'), ('f2', '<i4')], align=True)

In [162]:
np.result_type(np.dtype("i, i", np.dtype("i, i", align=True)))

dtype([('f0', '<i4'), ('f1', '<i4')], align=True)

In [164]:
recordarr = np.rec.array([(1, 2., 'Hello'), (2, 3., "World")],
                         dtype=[('foo', 'i4'),('bar', 'f4'), ('baz', 'S2')])
recordarr

rec.array([(1, 2., b'He'), (2, 3., b'Wo')],
          dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S2')])

In [166]:
recordarr.baz

array([b'He', b'Wo'], dtype='|S2')

In [170]:
recordarr[1:2].foo

array([2], dtype=int32)

In [172]:
recordarr[0].foo

1

In [175]:
arr = np.array([(1, 2., 'Hello'), (2, 3., 'World')],
               dtype=[('foo', 'i4'), ('bar', 'f4'), ('baz', 'S10')])
arr, type(arr)

(array([(1, 2., b'Hello'), (2, 3., b'World')],
       dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')]),
 numpy.ndarray)

In [176]:
recordarr = np.rec.array(arr)
recordarr, recordarr.dtype

(rec.array([(1, 2., b'Hello'), (2, 3., b'World')],
           dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')]),
 dtype((numpy.record, [('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])))

In [179]:
recordarr = arr.view(dtype=np.dtype((np.record, arr.dtype)),
                     type=np.recarray)
recordarr, type(recordarr)

(rec.array([(1, 2., b'Hello'), (2, 3., b'World')],
           dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')]),
 numpy.recarray)

In [180]:
recordarr1 = arr.view(np.recarray)

recordarr == recordarr1

rec.array([ True,  True],
          dtype=bool)

In [181]:
recordarr = np.rec.array([('Hello', (1, 2)), ("World", (3, 4))],
                dtype=[('foo', 'S6'),('bar', [('A', int), ('B', int)])])

type(recordarr.foo), type(recordarr.bar)

(numpy.ndarray, numpy.recarray)

In [182]:
recordarr

rec.array([(b'Hello', (1, 2)), (b'World', (3, 4))],
          dtype=[('foo', 'S6'), ('bar', [('A', '<i8'), ('B', '<i8')])])

In [188]:
from numpy.lib import recfunctions as rfn

new_field_names = ['weight', 'height']
new_data = (np.array([55.0, 85.5]), np.array([160, 180]))

new_data = rfn.append_fields(recordarr, new_field_names, new_data, usemask=False)
new_data

array([(b'Hello', (1, 2), 55. , 160), (b'World', (3, 4), 85.5, 180)],
      dtype=[('foo', 'S6'), ('bar', [('A', '<i8'), ('B', '<i8')]), ('weight', '<f8'), ('height', '<i8')])

In [189]:
from numpy.lib import recfunctions as rfn

b = np.array([(1, 2, 5), (4, 5, 7), (7, 8 ,11), (10, 11, 12)],
             dtype=[('x', 'i4'), ('y', 'f4'), ('z', 'f8')])
rfn.apply_along_fields(np.mean, b)

array([ 2.66666667,  5.33333333,  8.66666667, 11.        ])

In [190]:
rfn.apply_along_fields(np.mean, b[['x', 'z']])

array([ 3. ,  5.5,  9. , 11. ])