In [1]:
import numpy as np

In [2]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
x, x.shape

(array([('Rex', 9, 81.), ('Fido', 3, 27.)],
       dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')]),
 (2,))

In [3]:
x[0], x[1]

(('Rex', 9, 81.), ('Fido', 3, 27.))

In [4]:
x['age']

array([9, 3], dtype=int32)

In [5]:
x['name']

array(['Rex', 'Fido'], dtype='<U10')

In [6]:
np.dtype('i8, f4, S3')

dtype([('f0', '<i8'), ('f1', '<f4'), ('f2', 'S3')])

In [7]:
np.dtype('3int8, float32, (2, 3)float64')

dtype([('f0', 'i1', (3,)), ('f1', '<f4'), ('f2', '<f8', (2, 3))])

In [8]:
np.dtype({'names': ['col1', 'col2'], 'formats': ['i4', 'f4']})

dtype([('col1', '<i4'), ('col2', '<f4')])

In [9]:
np.dtype({'names': ['col1', 'col2'],
          'formats': ['i4', 'f4'],
          'offsets': [0, 4],
          'itemsize': 12})

dtype({'names': ['col1', 'col2'], 'formats': ['<i4', '<f4'], 'offsets': [0, 4], 'itemsize': 12})

In [10]:
np.dtype({'col1': ('i1', 0), 'col2': ('f4', 1)})

dtype([('col1', 'i1'), ('col2', '<f4')])

In [11]:
d = np.dtype([('x', 'i1'), ('y', 'f4'), ('z', '<datetime64'), ('a', 'c16'), ('b', 'c8')])
d.names, d.type, d['x'], d['z'], d['a']

(('x', 'y', 'z', 'a', 'b'),
 numpy.void,
 dtype('int8'),
 dtype('<M8'),
 dtype('complex128'))

In [12]:
d.fields

mappingproxy({'x': (dtype('int8'), 0),
              'y': (dtype('float32'), 1),
              'z': (dtype('<M8'), 5),
              'a': (dtype('complex128'), 13),
              'b': (dtype('complex64'), 29)})

In [13]:
def print_offsets(d):
    print("offsets:", [d.fields[name][1] for name in d.names])
    print("itemsize:", d.itemsize)
print_offsets(d)

offsets: [0, 1, 5, 13, 29]
itemsize: 37


In [14]:
print_offsets(np.dtype('u1, u1, i4, u1, i8, u2', align=True))

offsets: [0, 1, 4, 8, 16, 24]
itemsize: 32


In [15]:
np.dtype([(('my name', 'my'), 'f4')])

dtype([(('my name', 'my'), '<f4')])

In [16]:
d = np.dtype({'name': ('i4', 0, 'my name'), "surname": ('i8', 0, 'my surname')})
d

dtype({'names': ['name', 'surname'], 'formats': ['<i4', '<i8'], 'offsets': [0, 0], 'titles': ['my name', 'my surname'], 'itemsize': 8})

In [17]:
d.name, d['name'], d.fields

('void64',
 dtype('int32'),
 mappingproxy({'name': (dtype('int32'), 0, 'my name'),
               'my name': (dtype('int32'), 0, 'my name'),
               'surname': (dtype('int64'), 0, 'my surname'),
               'my surname': (dtype('int64'), 0, 'my surname')}))

In [18]:
for name in d.names:
    print(d.fields[name][:2])

(dtype('int32'), 0)
(dtype('int64'), 0)


In [19]:
x = np.array([(1, 2, 3), (4, 5, 6)], dtype='i8, f4, f8')
x[1] = (7, 8, 9)
x

array([(1, 2., 3.), (7, 8., 9.)],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '<f8')])

In [20]:
x = np.zeros(2, dtype='i8, f4, ?, S1')
x[:] = 3
x

array([(3, 3.,  True, b'3'), (3, 3.,  True, b'3')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [21]:
x[:] = np.arange(2)
x

array([(0, 0., False, b'0'), (1, 1.,  True, b'1')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [22]:
twofield = np.zeros(2, dtype=[('A', 'i4'), ('B', 'i4')])
onefield = np.zeros(2, dtype=[('A', 'i4')])
nostruct = np.zeros(2, dtype='i4')
nostruct, onefield, twofield

(array([0, 0], dtype=int32),
 array([(0,), (0,)], dtype=[('A', '<i4')]),
 array([(0, 0), (0, 0)], dtype=[('A', '<i4'), ('B', '<i4')]))

In [23]:
nostruct[:] = onefield
nostruct

array([0, 0], dtype=int32)

In [24]:
a = np.zeros(3, dtype=[('a', 'i8'), ('b', 'f4'), ('c', 'S3')])
b = np.ones(3, dtype=[('x', 'f4'), ('y', 'S3'), ('z', 'O')])
a, b

(array([(0, 0., b''), (0, 0., b''), (0, 0., b'')],
       dtype=[('a', '<i8'), ('b', '<f4'), ('c', 'S3')]),
 array([(1., b'1', 1), (1., b'1', 1), (1., b'1', 1)],
       dtype=[('x', '<f4'), ('y', 'S3'), ('z', 'O')]))

In [25]:
b[:] = a
b

array([(0., b'0.0', b''), (0., b'0.0', b''), (0., b'0.0', b'')],
      dtype=[('x', '<f4'), ('y', 'S3'), ('z', 'O')])

In [26]:
x = np.array([(1, 2), (3, 4)], dtype=[('foo', 'i8'), ('bar', 'f4')])
x['foo'], type(x['foo'])

(array([1, 3]), numpy.ndarray)

In [27]:
x['bar']

array([2., 4.], dtype=float32)

In [28]:
x['foo'] = 10
x

array([(10, 2.), (10, 4.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [29]:
y = x['bar']
y[:] = np.exp(1)
x

array([(10, 2.7182817), (10, 2.7182817)],
      dtype=[('foo', '<i8'), ('bar', '<f4')])

In [30]:
x = np.zeros((2, 2), dtype=[('a', np.int32), ('b', np.float64, (3, 3))])
x['a'].shape

(2, 2)

In [31]:
x

array([[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
       [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]],
      dtype=[('a', '<i4'), ('b', '<f8', (3, 3))])

In [32]:
x['b'].shape

(2, 2, 3, 3)

In [33]:
a = np.zeros(3, dtype=[('a', 'i4'), ('b', 'i4'), ('c', 'f4')])
a, a.shape

(array([(0, 0, 0.), (0, 0, 0.), (0, 0, 0.)],
       dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<f4')]),
 (3,))

In [34]:
a['a'], a['a'].shape

(array([0, 0, 0], dtype=int32), (3,))

In [35]:
a[['a']], a[['a']].shape

(array([(0,), (0,), (0,)],
       dtype={'names': ['a'], 'formats': ['<i4'], 'offsets': [0], 'itemsize': 12}),
 (3,))

In [36]:
a[['a', 'c']], a[['a', 'c']].shape

(array([(0, 0.), (0, 0.), (0, 0.)],
       dtype={'names': ['a', 'c'], 'formats': ['<i4', '<f4'], 'offsets': [0, 8], 'itemsize': 12}),
 (3,))

In [37]:
a[['b']]

array([(0,), (0,), (0,)],
      dtype={'names': ['b'], 'formats': ['<i4'], 'offsets': [4], 'itemsize': 12})

In [38]:
# a[['a', 'c']].view('i8')  # ValueError

In [39]:
from numpy.lib.recfunctions import repack_fields
repack_fields(a[['a', 'c']]).view('i8')

array([0, 0, 0])

In [40]:
b = np.zeros(3, dtype=[('x', 'f4'), ('y', 'f4'), ('z', 'f4')])
b[['x', 'z']].view('i4'), b['x'].view('i4')

(array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([0, 0, 0], dtype=int32))

In [41]:
from numpy.lib.recfunctions import structured_to_unstructured
structured_to_unstructured(b[['x', 'z']])

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [42]:
a[['a', 'c']] = (2, 3)
a

array([(2, 0, 3.), (2, 0, 3.), (2, 0, 3.)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<f4')])

In [43]:
a[['a', 'c']] = a[['c', 'a']]
a

array([(3, 0, 2.), (3, 0, 2.), (3, 0, 2.)],
      dtype=[('a', '<i4'), ('b', '<i4'), ('c', '<f4')])

In [44]:
x = np.array([1., 2., 3.], dtype='i1, f4, f8')
scalar = x[0]
scalar, x

((1, 1., 1.),
 array([(1, 1., 1.), (2, 2., 2.), (3, 3., 3.)],
       dtype=[('f0', 'i1'), ('f1', '<f4'), ('f2', '<f8')]))

In [45]:
type(scalar)

numpy.void

In [46]:
x = np.array([(1, 2), (3, 4)], dtype=[('foo', 'i1'), ('bar', 'f4')])
s = x[1]
s['bar'] = np.exp(1)
x

array([(1, 2.       ), (3, 2.7182817)],
      dtype=[('foo', 'i1'), ('bar', '<f4')])

In [47]:
scalar = np.array([(1, 2., 3.)], dtype='i, f, f')[0]
scalar[0], scalar[0].dtype, type(scalar)

(1, dtype('int32'), numpy.void)

In [48]:
scalar.item(), type(scalar.item())

((1, 2.0, 3.0), tuple)

In [49]:
a = np.array([(1, 2), (2, 2)], dtype=[('a', 'i4'), ('b', 'i4')])
b = np.array([(1, 2), (2, 2)], dtype=[('a', 'f4'), ('b', 'f4')])
c = np.array([(1, 2), (2, 3)], dtype=[('a', 'i4'), ('b', 'i4')])
a == b, a == c

(array([ True,  True]), array([ True, False]))

In [50]:
np.result_type(np.dtype("i, >i"))

dtype([('f0', '<i4'), ('f1', '<i4')])

In [51]:
np.result_type(np.dtype("i, i"), np.dtype("i, >i"))

dtype([('f0', '<i4'), ('f1', '<i4')])

In [52]:
dt = np.dtype("i1, V3, i4, V1")[["f0", "f2"]]
dt

dtype({'names': ['f0', 'f2'], 'formats': ['i1', '<i4'], 'offsets': [0, 4], 'itemsize': 9})

In [53]:
np.result_type(dt)

dtype([('f0', 'i1'), ('f2', '<i4')])

In [54]:
dt = np.dtype("i1, V8, i4, V1", align=True)[["f0", "f2"]]  # `V3` 3 bytes of padding
dt

dtype({'names': ['f0', 'f2'], 'formats': ['i1', '<i4'], 'offsets': [0, 12], 'itemsize': 20}, align=True)

In [55]:
np.result_type(dt)

dtype([('f0', 'i1'), ('f2', '<i4')], align=True)

In [56]:
np.result_type(np.dtype("i, i", np.dtype("i, i", align=True)))

dtype([('f0', '<i4'), ('f1', '<i4')], align=True)

In [57]:
recordarr = np.rec.array([(1, 2., 'Hello'), (2, 3., "World")],
                         dtype=[('foo', 'i4'),('bar', 'f4'), ('baz', 'S2')])
recordarr

rec.array([(1, 2., b'He'), (2, 3., b'Wo')],
          dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S2')])

In [58]:
recordarr.baz

array([b'He', b'Wo'], dtype='|S2')

In [59]:
recordarr[1:2].foo

array([2], dtype=int32)

In [60]:
recordarr[0].foo

1

In [61]:
arr = np.array([(1, 2., 'Hello'), (2, 3., 'World')],
               dtype=[('foo', 'i4'), ('bar', 'f4'), ('baz', 'S10')])
arr, type(arr)

(array([(1, 2., b'Hello'), (2, 3., b'World')],
       dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')]),
 numpy.ndarray)

In [62]:
recordarr = np.rec.array(arr)
recordarr, recordarr.dtype

(rec.array([(1, 2., b'Hello'), (2, 3., b'World')],
           dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')]),
 dtype((numpy.record, [('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])))

In [63]:
recordarr = arr.view(dtype=np.dtype((np.record, arr.dtype)),
                     type=np.recarray)
recordarr, type(recordarr)

(rec.array([(1, 2., b'Hello'), (2, 3., b'World')],
           dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')]),
 numpy.recarray)

In [64]:
recordarr1 = arr.view(np.recarray)

recordarr == recordarr1

rec.array([ True,  True],
          dtype=bool)

In [65]:
recordarr = np.rec.array([('Hello', (1, 2)), ("World", (3, 4))],
                dtype=[('foo', 'S6'),('bar', [('A', int), ('B', int)])])

type(recordarr.foo), type(recordarr.bar)

(numpy.ndarray, numpy.recarray)

In [66]:
recordarr

rec.array([(b'Hello', (1, 2)), (b'World', (3, 4))],
          dtype=[('foo', 'S6'), ('bar', [('A', '<i8'), ('B', '<i8')])])

In [67]:
from numpy.lib import recfunctions as rfn

new_field_names = ['weight', 'height']
new_data = (np.array([55.0, 85.5]), np.array([160, 180]))

new_data = rfn.append_fields(recordarr, new_field_names, new_data, usemask=False)
new_data

array([(b'Hello', (1, 2), 55. , 160), (b'World', (3, 4), 85.5, 180)],
      dtype=[('foo', 'S6'), ('bar', [('A', '<i8'), ('B', '<i8')]), ('weight', '<f8'), ('height', '<i8')])

In [68]:
from numpy.lib import recfunctions as rfn

b = np.array([(1, 2, 5), (4, 5, 7), (7, 8 ,11), (10, 11, 12)],
             dtype=[('x', 'i4'), ('y', 'f4'), ('z', 'f8')])
rfn.apply_along_fields(np.mean, b)

array([ 2.66666667,  5.33333333,  8.66666667, 11.        ])

In [69]:
rfn.apply_along_fields(np.mean, b[['x', 'z']])

array([ 3. ,  5.5,  9. , 11. ])

In [75]:
c = np.array([(np.exp(1))], dtype=[('euler', 'f4')])
c

array([(2.7182817,)], dtype=[('euler', '<f4')])

In [76]:
rfn.assign_fields_by_name(c, b, zero_unassigned=True)
c

array([(0.,)], dtype=[('euler', '<f4')])

In [91]:
import numpy as np
from numpy.lib import recfunctions as rfn

# Example structured array
data = np.array([(1, 'John', 25),
                 (2, 'Alice', 30),
                 (3, 'Bob', 35),
                 (4, 'Bob', 70)],
                dtype=[('id', int), ('name', 'U10'), ('age', int)])

rfn.drop_fields(data, 'age')

array([(1, 'John'), (2, 'Alice'), (3, 'Bob'), (4, 'Bob')],
      dtype=[('id', '<i8'), ('name', '<U10')])

In [108]:
ndtype = [('a', int)]
a = np.ma.array([1, 1, 1, 2, 2, 3, 3, 3],
        mask=[0, 0, 1, 0, 0, 0, 0, 1]).view(ndtype)
a

masked_array(data=[(1,), (1,), (--,), (2,), (2,), (3,), (3,), (--,)],
             mask=[(False,), (False,), ( True,), (False,), (False,),
                   (False,), (False,), ( True,)],
       fill_value=(999999,),
            dtype=[('a', '<i8')])

In [109]:
rfn.find_duplicates(a, ignoremask=True, return_index=True)

(masked_array(data=[(1,), (1,), (2,), (2,), (3,), (3,)],
              mask=[(False,), (False,), (False,), (False,), (False,),
                    (False,)],
        fill_value=(999999,),
             dtype=[('a', '<i8')]),
 array([0, 1, 3, 4, 5, 6]))

In [121]:
from numpy.lib import recfunctions as rfn
ndtype = np.dtype([('a', '<i4'), ('b', [('ba', '<f8'), ('bb', '<i4')]), ('c', '<c8')])
ndtype, rfn.flatten_descr(ndtype)

(dtype([('a', '<i4'), ('b', [('ba', '<f8'), ('bb', '<i4')]), ('c', '<c8')]),
 (('a', dtype('int32')),
  ('ba', dtype('float64')),
  ('bb', dtype('int32')),
  ('c', dtype('complex64'))))

In [125]:
rfn.get_fieldstructure(ndtype)

{'a': [], 'b': [], 'ba': ['b'], 'bb': ['b'], 'c': []}

In [126]:
rfn.get_names(ndtype)

('a', ('b', ('ba', 'bb')), 'c')

In [127]:
from numpy.lib import recfunctions as rfn

rfn.get_names_flat(np.empty((1,), dtype=[('A', int), ('B', str)]).dtype) is None

False

In [128]:
rfn.get_names_flat(np.empty((1,), dtype=[('A', int), ('B', str)]).dtype)

('A', 'B')

In [129]:
rfn.get_names_flat(ndtype)

('a', 'b', 'ba', 'bb', 'c')

In [130]:
array1 = np.array([(1, 'Alice'), (2, 'Bob'), (3, 'Charlie')],
                  dtype=[('ID', '<i1'), ('Name', '<U10')])
array2 = np.array([(2, 25), (3, 30), (4, 40)],
                  dtype=[('ID', '<i4'), ('Age', '<i4')])

rfn.join_by('ID', array1, array2, jointype='inner')

masked_array(data=[(2, 'Bob', 25), (3, 'Charlie', 30)],
             mask=[(False, False, False), (False, False, False)],
       fill_value=(999999, 'N/A', 999999),
            dtype=[('ID', '<i4'), ('Name', '<U10'), ('Age', '<i4')])

In [131]:
rfn.merge_arrays((array1, array2))

array([((1, 'Alice'), (2, 25)), ((2, 'Bob'), (3, 30)),
       ((3, 'Charlie'), (4, 40))],
      dtype=[('f0', [('ID', 'i1'), ('Name', '<U10')]), ('f1', [('ID', '<i4'), ('Age', '<i4')])])

In [143]:
from numpy.lib import recfunctions as rfn

array3 = np.array([(1, 'Frackowiak')],
                  dtype=[('ID', '<i4'), ('Surname', '<U10')])

rfn.rec_append_fields(array1, names='', data=array3)

rec.array([(1, 'Alice', (     1, 'Frackowiak')),
           (2, 'Bob', (999999, 'N/A')), (3, 'Charlie', (999999, 'N/A'))],
          dtype=[('ID', 'i1'), ('Name', '<U10'), ('f0', [('ID', '<i4'), ('Surname', '<U10')])])

In [146]:
array1

array([(1, 'Alice'), (2, 'Bob'), (3, 'Charlie')],
      dtype=[('ID', 'i1'), ('Name', '<U10')])

In [147]:
rfn.rec_drop_fields(array1, drop_names='Name')

rec.array([(1,), (2,), (3,)],
          dtype=[('ID', 'i1')])

In [150]:
from numpy.lib import recfunctions as rfn

a = np.array([(1, 10.), (2, 20.)], dtype=[('A', np.int64), ('B', np.float64)])
b = np.zeros((3,), dtype=a.dtype)
a, b

(array([(1, 10.), (2, 20.)], dtype=[('A', '<i8'), ('B', '<f8')]),
 array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')]))

In [151]:
rfn.recursive_fill_fields(input=a, output=b)

array([(1, 10.), (2, 20.), (0,  0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [153]:
rfn.rename_fields(a, {'A': 'a', 'B': 'b'})

array([(1, 10.), (2, 20.)], dtype=[('a', '<i8'), ('b', '<f8')])

In [155]:
from numpy.lib import recfunctions as rfn
def print_offsets(d):
    print("offsets:", [d.fields[name][1] for name in d.names])
    print("itemsize:", d.itemsize)

dt = np.dtype('u1, <i8, <f8', align=True)
dt

dtype([('f0', 'u1'), ('f1', '<i8'), ('f2', '<f8')], align=True)

In [156]:
print(print_offsets(dt))

offsets: [0, 8, 16]
itemsize: 24
None


In [157]:
packed_dt = rfn.repack_fields(dt)
packed_dt

dtype([('f0', 'u1'), ('f1', '<i8'), ('f2', '<f8')])

In [159]:
print_offsets(packed_dt)

offsets: [0, 1, 9]
itemsize: 17


In [166]:
dt.fields, packed_dt.fields

(mappingproxy({'f0': (dtype('uint8'), 0),
               'f1': (dtype('int64'), 8),
               'f2': (dtype('float64'), 16)}),
 mappingproxy({'f0': (dtype('uint8'), 0),
               'f1': (dtype('int64'), 1),
               'f2': (dtype('float64'), 9)}))

In [167]:
from numpy.lib import recfunctions as rfn
a = np.ones(4, dtype=[('a', 'i4'), ('b', 'f8'), ('c', 'u1')])
rfn.require_fields(a, [('b', 'f4'), ('c', 'u1')])

array([(1., 1), (1., 1), (1., 1), (1., 1)],
      dtype=[('b', '<f4'), ('c', 'u1')])

In [168]:
rfn.require_fields(a, [('b', 'f4'), ('newf', 'u1')])

array([(1., 0), (1., 0), (1., 0), (1., 0)],
      dtype=[('b', '<f4'), ('newf', 'u1')])

In [169]:
from numpy.lib import recfunctions as rfn

x = np.array([1, 2,])
rfn.stack_arrays(x) is x

True

In [172]:
z = np.array([('A', 1), ('B', 2)], dtype=[('A', '|S3'), ('B', float)])
zz = np.array([('a', 10., 100.), ('b', 20., 200.), ('c', 30., 300.)],
              dtype=[('A', '|S3'), ('B', np.double), ('C', np.double)])
test = rfn.stack_arrays((z, zz))
test

masked_array(data=[(b'A', 1.0, --), (b'B', 2.0, --), (b'a', 10.0, 100.0),
                   (b'b', 20.0, 200.0), (b'c', 30.0, 300.0)],
             mask=[(False, False,  True), (False, False,  True),
                   (False, False, False), (False, False, False),
                   (False, False, False)],
       fill_value=(b'N/A', 1.e+20, 1.e+20),
            dtype=[('A', 'S3'), ('B', '<f8'), ('C', '<f8')])

In [189]:
from numpy.lib import recfunctions as rfn
a = np.zeros(4, dtype=[('a', 'i4', 2), ('b', '<u2'), ('c', 'f4', 2)])
a

array([([0, 0], 0, [0., 0.]), ([0, 0], 0, [0., 0.]),
       ([0, 0], 0, [0., 0.]), ([0, 0], 0, [0., 0.])],
      dtype=[('a', '<i4', (2,)), ('b', '<u2'), ('c', '<f4', (2,))])

In [190]:
rfn.structured_to_unstructured(a)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [194]:
b = np.array([(1, 2, 5), (4, 5, 8), (10, 11, 13)],
             dtype=[('x', 'i4'), ('y', 'f4'), ('z', 'f8')])
b[['x', 'z']]

array([( 1,  5.), ( 4,  8.), (10, 13.)],
      dtype={'names': ['x', 'z'], 'formats': ['<i4', '<f8'], 'offsets': [0, 8], 'itemsize': 16})

In [203]:
np.median(rfn.structured_to_unstructured(b[['x', 'z']]), axis=1)

array([ 3. ,  6. , 11.5])

In [218]:
from numpy.lib import recfunctions as rfn

dt = np.dtype([('a', 'i1', 2), ('b', 'f4, u1'), ('c', 'f4')])
a = np.arange(20).reshape((4, 5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [219]:
rfn.unstructured_to_structured(a, dt)

array([([ 0,  1], ( 2.,  3),  4.), ([ 5,  6], ( 7.,  8),  9.),
       ([10, 11], (12., 13), 14.), ([15, 16], (17., 18), 19.)],
      dtype=[('a', 'i1', (2,)), ('b', [('f0', '<f4'), ('f1', 'u1')]), ('c', '<f4')])