In [1]:
import numpy as np

In [2]:
np.array([0,1,2,3]) + np.array([1, 2, -1, 2])

array([1, 3, 1, 5])

In [5]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.add.reduce(x, axis=0), np.add.reduce(x, axis=1), np.add.reduce(x, axis=(0, 1))

(array([ 9, 12, 15]), array([ 3, 12, 21]), 36)

In [13]:
x.dtype, x

(dtype('int64'),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]))

In [14]:
np.multiply.reduce(x, dtype=float)

array([ 0., 28., 80.])

In [15]:
y = np.zeros(3, dtype=int)
y

array([0, 0, 0])

In [16]:
np.multiply.reduce(x, dtype=float, out=y)

array([ 0, 28, 80])

In [17]:
y

array([ 0, 28, 80])