In [1]:
import numpy as np

In [2]:
np.array([0,1,2,3]) + np.array([1, 2, -1, 2])

array([1, 3, 1, 5])

In [3]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.add.reduce(x, axis=0), np.add.reduce(x, axis=1), np.add.reduce(x, axis=(0, 1))

(array([ 9, 12, 15]), array([ 3, 12, 21]), 36)

In [5]:
x.dtype, x

(dtype('int64'),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]))

In [6]:
np.multiply.reduce(x, dtype=float)

array([ 0., 28., 80.])

In [7]:
y = np.zeros(3, dtype=int)
y

array([0, 0, 0])

In [8]:
np.multiply.reduce(x, dtype=float, out=y)

array([ 0, 28, 80])

In [9]:
y

array([ 0, 28, 80])

In [11]:
np.result_type(3), np.result_type(3, np.arange(7))

(dtype('int64'), dtype('int64'))

In [16]:
np.result_type(3, np.arange(7, dtype='i1')), np.result_type(3.0, np.arange(7, dtype='i1'))

(dtype('int8'), dtype('float64'))

In [14]:
np.result_type('i4', 'c8')

dtype('complex128')

In [23]:
np.promote_types('i4', 'c8'), np.promote_types('i4', 'f4'), np.promote_types('i1', 'f4')

(dtype('complex128'), dtype('float64'), dtype('float32'))

In [26]:
np.promote_types('bool', 'i1'), np.promote_types('bool', 'bool')

(dtype('int8'), dtype('bool'))

In [36]:
np.min_scalar_type(10), np.min_scalar_type(10.0), np.min_scalar_type(190)

(dtype('uint8'), dtype('float16'), dtype('uint8'))

In [38]:
np.min_scalar_type(1j), np.min_scalar_type(True)

(dtype('complex64'), dtype('bool'))

In [47]:
x = np.ldexp(5, np.arange(4))  # 5, 5*2, 5*3, 5*4
x

array([ 5., 10., 20., 40.], dtype=float16)

In [45]:
np.ldexp(*np.frexp(x))

array([ 5., 10., 20., 40.], dtype=float16)

In [48]:
np.frexp(x)  # x = mantissa * 2**exponent where mantissa is float [−1,−0.5]∪[0.5,1)

(array([0.625, 0.625, 0.625, 0.625], dtype=float16),
 array([3, 4, 5, 6], dtype=int32))

In [49]:
x = np.array([1.0, 2.0, 4.0, 8.0, 16.0, 0.1])
mantissa, exponent = np.frexp(x)

""""
`0.1` is represented as 0.8 * 2**-3 where 0.8 is a mantissa and -3 is a exponent
"""

print("Original array:", x)
print("Mantissas:", mantissa)
print("Exponents:", exponent)

Original array: [ 1.   2.   4.   8.  16.   0.1]
Mantissas: [0.5 0.5 0.5 0.5 0.5 0.8]
Exponents: [ 1  2  3  4  5 -3]


In [52]:
mark = {False: ' -', True: ' Y'}
def print_table(ntypes):
    print('X ' + ' '.join(ntypes))
    for row in ntypes:
        print(row, end='')
        for col in ntypes:
            print(mark[np.can_cast(row, col)], end='')
        print()

print_table(np.typecodes['All'])

X ? b h i l q p B H I L Q P e f d g F D G S U V O M m
? Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y - Y
b - Y Y Y Y Y Y - - - - - - Y Y Y Y Y Y Y Y Y Y Y - Y
h - - Y Y Y Y Y - - - - - - - Y Y Y Y Y Y Y Y Y Y - Y
i - - - Y Y Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
l - - - - Y Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
q - - - - Y Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
p - - - - Y Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
B - - Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y - Y
H - - - Y Y Y Y - Y Y Y Y Y - Y Y Y Y Y Y Y Y Y Y - Y
I - - - - Y Y Y - - Y Y Y Y - - Y Y - Y Y Y Y Y Y - Y
L - - - - - - - - - - Y Y Y - - Y Y - Y Y Y Y Y Y - -
Q - - - - - - - - - - Y Y Y - - Y Y - Y Y Y Y Y Y - -
P - - - - - - - - - - Y Y Y - - Y Y - Y Y Y Y Y Y - -
e - - - - - - - - - - - - - Y Y Y Y Y Y Y Y Y Y Y - -
f - - - - - - - - - - - - - - Y Y Y Y Y Y Y Y Y Y - -
d - - - - - - - - - - - - - - - Y Y - Y Y Y Y Y Y - -
g - - - - - - - - - - - - - - - - Y - - Y Y Y Y Y - -
F - - - - - - - - - - - - - 

In [56]:
np.setbufsize(8192)

a = np.arange(1000)
b = np.sin(a)
c = a + b

print(c)

[  0.           1.84147098   2.90929743   3.14112001   3.2431975
   4.04107573   5.7205845    7.6569866    8.98935825   9.41211849
   9.45597889  10.00000979  11.46342708  13.42016704  14.99060736
  15.65028784  15.71209668  16.03860251  17.24901275  19.14987721
  20.91294525  21.83665564  21.99114869  22.1537796   23.09442164
  24.86764825  26.76255845  27.95637593  28.27090579  28.33636612
  29.01196838  30.59596235  32.55142668  33.99991186  34.52908269
  34.57181733  35.00822115  36.35646187  38.29636858  39.96379539
  40.74511316  40.84137733  41.08347845  42.16822526  44.01770193
  45.85090352  46.90178835  47.12357312  47.23174534  48.04624735
  49.73762515  51.67022918  52.98662759  53.39592515  53.44121095
  54.00024483  55.478449    57.43616476  58.99287265  59.63673801
  59.69518938  60.03388223  61.2608193   63.1673557   64.92002604
  65.82682868  65.97344885  66.14448002  67.10207232  68.88521519
  70.77389068  71.95105465  72.25382336  72.32322804  73.01485374
  74.612218

In [64]:
orig_settings = np.seterr(all='ignore')  # seterr to known value
x = (np.int16(32000) * np.int16(3))
x, type(x)

(30464, numpy.int16)

In [62]:
np.seterr(over='raise')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [65]:
old_settings = np.seterr(all='warn')
np.int16(32000) * np.int16(3)

/tmp/ipykernel_1935/1633091125.py:2: RuntimeWarning: overflow encountered in scalar multiply
  np.int16(32000) * np.int16(3)


30464

In [67]:
np.seterr(over='raise')
np.int16(32000) * np.int16(3)  # maximum value can be 32767, the product is `96000`

FloatingPointError: overflow encountered in scalar multiply

In [68]:
class Log:
    def write(self, msg):
        print("LOG: %s" % msg)


log = Log()
saved_handler = np.seterrcall(log)
save_err = np.seterr(all='log')

In [69]:
np.array([1, 2, 3]) / 0.0

LOG: Warning: divide by zero encountered in divide



array([inf, inf, inf])

In [73]:
class DiagonalArray:
    def __init__(self, N, value):
        self._N = N
        self._i = value
    def __repr__(self):
        return f"{self.__class__.__name__}(N={self._N}, value={self._i})"
    def __array__(self, dtype=None, copy=None):
        if copy is False:
            raise ValueError(
                "`copy=False` isn't suppoerted. A copy is always created."
            )
        return self._i * np.eye(self._N, dtype=dtype)

In [74]:
arr = DiagonalArray(5, 1)
arr  # calls __repr__

DiagonalArray(N=5, value=1)

In [75]:
np.asarray(arr)  # calls __array__

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])